import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser', DB_VERSION=1, STORE='games';
const PREF='chess-analyser-pref:';
function preference(k,fallback){return localStorage.getItem(PREF+k)||fallback}
function pieceSvg(color,type,extraClass=''){
  const code={p:'P',r:'R',n:'N',b:'B',q:'Q',k:'K'}[type],side=color==='w'?'w':'b',cls=color==='w'?'whitePiece':'blackPiece';
  const folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'};
  const folder=folders[preference('pieces','neo')]||folders.neo;
  const src=`https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${side}${code}.svg`;
  return `<img class="piece ${cls} ${extraClass}" src="${src}" draggable="false" alt="" aria-hidden="true">`;
}
let selectedGame=null, mainMoves=[], currentChess=new Chess(), currentPly=0, orientation='white', selectedSquare=null, legalTargets=[], variation=false, lastMove=null;
const evalCache=new Map();
let audioCtx=null;
function playMoveSound(capture=false){if(preference('sound','on')==='off')return;try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=capture?235:330;g.gain.setValueAtTime(.045,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.07);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.075)}catch{}}
queueMicrotask(()=>{const e=$('enginePieceIcon');if(e)e.innerHTML=pieceSvg('b','n')});
function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'_key'});s.createIndex('end_time','end_time')}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function putGames(games){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const g of games){g._key=g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`;s.put(g)}tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function allGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result.sort((a,b)=>(b.end_time||0)-(a.end_time||0)))};r.onerror=()=>{db.close();reject(r.error)}})}
async function getJSON(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function gameKey(g){return g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`}
function syncMetaKey(u){return `chess-sync-meta:${u.toLowerCase()}`}
function readSyncMeta(u){try{return JSON.parse(localStorage.getItem(syncMetaKey(u))||'null')||{archives:[],lastSync:0}}catch{return {archives:[],lastSync:0}}}
function writeSyncMeta(u,meta){localStorage.setItem(syncMetaKey(u),JSON.stringify(meta))}
async function sync({automatic=false}={}){const button=$('sync');try{button.disabled=true;const u=$('user').value.trim();if(!u)throw new Error('Enter a Chess.com username');localStorage.setItem('chess-username',u);$('status').textContent=automatic?'Checking Chess.com for new games…':'Finding Chess.com archives…';const a=await getJSON(`https://api.chess.com/pub/player/${encodeURIComponent(u)}/games/archives`);const archives=a.archives||[];const before=await allGames();const existing=new Set(before.map(gameKey));let meta=readSyncMeta(u);if(before.length&&(!meta.archives||!meta.archives.length))meta.archives=[...archives];const known=new Set(meta.archives||[]),neverSynced=archives.filter(x=>!known.has(x)),recent=archives.slice(-2);let targets=[...new Set([...neverSynced,...recent])];if(!before.length)targets=[...archives];let newCount=0;for(let i=0;i<targets.length;i++){$('status').textContent=`${automatic?'Auto-sync':'Sync'} ${i+1}/${targets.length} · ${newCount} new game${newCount===1?'':'s'}`;const d=await getJSON(targets[i]),batch=d.games||[];for(const g of batch){if(!existing.has(gameKey(g))){existing.add(gameKey(g));newCount++}}await putGames(batch)}const games=await allGames();renderGames(games,u);meta={archives:[...archives],lastSync:Date.now()};writeSyncMeta(u,meta);const time=new Date(meta.lastSync).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('status').textContent=newCount?`${newCount} new game${newCount===1?'':'s'} synced · ${games.length} saved · ${time}`:`Up to date · ${games.length} games saved · checked ${time}`}catch(e){$('status').textContent=(automatic?'Auto-sync failed: ':'Sync failed: ')+e.message}finally{button.disabled=false}}
function renderGames(games,u){$('games').innerHTML='';if(!games.length){$('games').innerHTML='<div class="game">No saved games yet.</div>';return}games.forEach(g=>{const isWhite=g.white.username.toLowerCase()===u.toLowerCase(),me=isWhite?g.white:g.black,opp=isWhite?g.black:g.white;const result=me.result==='win'?'Win':(['checkmated','resigned','timeout','lose'].includes(me.result)?'Loss':'Draw');const d=document.createElement('div');d.className='game';d.innerHTML=`<b>${me.username} ${me.rating??''}</b> — ${opp.username} ${opp.rating??''}<div class="muted">${result} · ${formatTimeControl(g.time_control)} · ${new Date((g.end_time||0)*1000).toLocaleString()}</div>`;d.onclick=()=>openGame(g,u);$('games').appendChild(d)})}
function formatTimeControl(tc){if(!tc)return 'Game';if(tc.includes('+')){const [s,i]=tc.split('+').map(Number);return `${Math.round(s/60)}+${i}`}const s=Number(tc);return Number.isFinite(s)?`${Math.round(s/60)} min`:tc}
function parseInitialFen(pgn){const m=pgn.match(/^\[FEN\s+"([^"]+)"\]/m);return m?m[1]:null}
function freshChess(){const fen=parseInitialFen(selectedGame?.pgn||'');return fen?new Chess(fen):new Chess()}
function freshFromPgn(pgn){const c=new Chess();c.loadPgn(pgn);return c}
function openGame(g,u){selectedGame=g;const parsed=freshFromPgn(g.pgn);mainMoves=parsed.history({verbose:true});orientation=g.white.username.toLowerCase()===u.toLowerCase()?'white':'black';currentPly=0;variation=false;selectedSquare=null;lastMove=null;currentChess=freshChess();$('libraryView').style.display='none';$('analysisView').style.display='block';$('gameTitle').textContent=`${g.white.username} ${g.white.rating??''} — ${g.black.username} ${g.black.rating??''}`;$('gameMeta').textContent=`${new Date((g.end_time||0)*1000).toLocaleString()} · ${formatTimeControl(g.time_control)} · ${g.rated?'Rated':'Casual'}`;renderAll();window.scrollTo(0,0)}
function gotoPly(ply){ply=Math.max(0,Math.min(mainMoves.length,ply));const old=currentPly;currentChess=freshChess();lastMove=null;for(let i=0;i<ply;i++){const m=mainMoves[i];lastMove=currentChess.move({from:m.from,to:m.to,promotion:m.promotion})}currentPly=ply;variation=false;selectedSquare=null;legalTargets=[];clearEval();renderAll();if(old!==ply)playMoveSound(lastMove?.captured!=null)}
function renderAll(){renderPlayers();renderBoard();renderMoves();$('variationNote').textContent=variation?'Exploring your variation. Use return to go back to the game.':''}
function renderPlayers(){const topColor=orientation==='white'?'black':'white',bottomColor=orientation,top=topColor==='white'?selectedGame.white:selectedGame.black,bottom=bottomColor==='white'?selectedGame.white:selectedGame.black;const h=(p,c)=>`<span class="playerName">${pieceSvg(c==='white'?'w':'b','p','playerPiece')}<span>${p.username}</span></span><span>${p.rating??''}</span>`;$('topPlayer').innerHTML=h(top,topColor);$('bottomPlayer').innerHTML=h(bottom,bottomColor)}
function squareOrder(){const files=orientation==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=orientation==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function renderBoard(){const b=$('board');b.innerHTML='';squareOrder().forEach(sq=>{const file=sq.charCodeAt(0)-97,rank=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(file+rank)%2?'light':'dark'}`;el.dataset.square=sq;if(selectedSquare===sq)el.classList.add('selected');if(lastMove&&(lastMove.from===sq||lastMove.to===sq))el.classList.add('last');const p=currentChess.get(sq);if(p)el.insertAdjacentHTML('beforeend',pieceSvg(p.color,p.type));el.onclick=()=>tapSquare(sq);b.appendChild(el)})}
function tapSquare(sq){if(selectedSquare){if(tryUserMove(selectedSquare,sq))return;selectedSquare=null;legalTargets=[]}const p=currentChess.get(sq);if(p&&p.color===currentChess.turn()){selectedSquare=sq;legalTargets=currentChess.moves({square:sq,verbose:true});renderBoard()}}
function tryUserMove(from,to){const moves=currentChess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!moves.length)return false;try{lastMove=currentChess.move({from,to,promotion:moves.some(m=>m.promotion)?'q':undefined});variation=true;selectedSquare=null;legalTargets=[];clearEval();renderAll();playMoveSound(lastMove?.captured!=null);return true}catch{return false}}
function renderMoves(){const box=$('moves');box.innerHTML='';for(let i=0;i<mainMoves.length;i+=2){const row=document.createElement('div');row.className='moveRow';row.innerHTML=`<div class="moveNo">${Math.floor(i/2)+1}.</div>`;for(let j=0;j<2;j++){const idx=i+j;if(idx<mainMoves.length){const btn=document.createElement('div');btn.className='move'+(!variation&&currentPly===idx+1?' active':'');btn.textContent=mainMoves[idx].san;btn.onclick=()=>gotoPly(idx+1);row.appendChild(btn)}else row.appendChild(document.createElement('div'))}box.appendChild(row)}}
function clearArrows(){$('analysisArrows').innerHTML=''}
function clearEval(){$('engineScore').textContent='—';$('engineSource').textContent='Ready';$('mobileScore').textContent='—';$('mobileSource').textContent='Ready';$('mobileLine').textContent='Tap Analyse to show the best move arrow.';$('bestLine').textContent='Choose a position and tap Analyse. The suggested move will be drawn directly on the board.';$('evalFill').style.height='50%';clearArrows()}
function scoreInfo(pv){if(pv?.mate!==undefined&&pv?.mate!==null&&Number(pv.mate)!==0){const mate=Number(pv.mate);return{whiteScore:mate>0?20:-20,label:(mate<0?'-':'')+'M'+Math.abs(mate)}}const whiteScore=(Number(pv?.cp)||0)/100;return{whiteScore,label:(whiteScore>=0?'+':'')+whiteScore.toFixed(2)}}
function firstUciMove(pv){const raw=String(pv?.moves||'').trim().split(/\s+/)[0]||'';return /^[a-h][1-8][a-h][1-8][qrbn]?$/.test(raw)?raw:null}
function squareCenter(sq){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),x=orientation==='white'?f:7-f,y=orientation==='white'?8-r:r-1;return{x:(x+.5)*100,y:(y+.5)*100}}
function drawEngineArrows(pvs){const svg=$('analysisArrows');svg.innerHTML='<defs><marker id="arr0" markerWidth="5" markerHeight="5" refX="4.1" refY="2.5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L5,2.5 L0,5 Z" fill="#8bc34a"/></marker><marker id="arr1" markerWidth="5" markerHeight="5" refX="4.1" refY="2.5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L5,2.5 L0,5 Z" fill="#f4c542"/></marker><marker id="arr2" markerWidth="5" markerHeight="5" refX="4.1" refY="2.5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L5,2.5 L0,5 Z" fill="#58a6ff"/></marker></defs>';pvs.slice(0,3).forEach((pv,i)=>{const u=firstUciMove(pv);if(!u)return;const a=squareCenter(u.slice(0,2)),b=squareCenter(u.slice(2,4)),dx=b.x-a.x,dy=b.y-a.y,len=Math.hypot(dx,dy)||1,ex=b.x-dx/len*22,ey=b.y-dy/len*22;svg.insertAdjacentHTML('beforeend',`<line x1="${a.x}" y1="${a.y}" x2="${ex}" y2="${ey}" stroke="${['#8bc34a','#f4c542','#58a6ff'][i]}" stroke-width="${i?12:16}" stroke-linecap="round" opacity=".88" marker-end="url(#arr${i})"/>`)})}
async function lichessCloud(fen){const r=await fetch(`https://lichess.org/api/cloud-eval?fen=${encodeURIComponent(fen)}&multiPv=3&variant=standard`,{headers:{Accept:'application/json'}});if(r.status===404)return null;if(!r.ok)throw new Error(`Cloud ${r.status}`);const j=await r.json(),pvs=(j.pvs||[]).slice(0,3);return pvs.length?{depth:j.depth,pv:pvs[0],pvs,source:'Lichess cloud'}:null}
async function liveStockfish(fen){const r=await fetch('https://chess-api.com/v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fen,depth:14,variants:1,maxThinkingTime:180})});if(!r.ok)throw new Error(`Live engine ${r.status}`);const j=await r.json(),whiteScore=j.eval!=null?Number(j.eval):Number(j.centipawns)/100,bestMove=j.move||j.lan||'',continuation=Array.isArray(j.continuationArr)?j.continuationArr.filter(Boolean):[],line=[bestMove,...continuation.filter((m,i)=>!(i===0&&m===bestMove))].filter(Boolean).join(' '),pv={cp:Number.isFinite(whiteScore)?Math.round(whiteScore*100):0,mate:j.mate,moves:line};return{depth:j.depth||14,pv,pvs:[pv],source:'Stockfish live'}}
function setAnalysing(on){for(const id of ['analyse','analyseMobile']){const b=$(id);b.disabled=on;b.classList.toggle('loading',on);b.textContent=on?'Analysing':'Analyse'}}
async function analysePosition(){const fen=currentChess.fen(),mode=preference('engine','auto'),cacheKey=mode+'|'+fen;if(evalCache.has(cacheKey)){showEval(evalCache.get(cacheKey));return}try{setAnalysing(true);let data=null;if(mode==='cloud'){data=await lichessCloud(fen);if(!data)throw new Error('No cloud evaluation for this position')}else if(mode==='stockfish'){data=await liveStockfish(fen)}else{try{data=await lichessCloud(fen)}catch{}if(!data)data=await liveStockfish(fen)}evalCache.set(cacheKey,data);showEval(data)}catch(e){$('bestLine').textContent=`Could not analyse this position: ${e.message}`;$('mobileLine').textContent='Analysis failed — tap to retry.'}finally{setAnalysing(false)}}
function showEval(data){const pvs=(data.pvs?.length?data.pvs:[data.pv]).filter(Boolean).slice(0,3),top=scoreInfo(pvs[0]);$('engineScore').textContent=$('mobileScore').textContent=top.label;$('engineSource').textContent=`${data.source} · depth ${data.depth??'—'}`;$('mobileSource').textContent=data.source;$('bestLine').textContent='Best: '+(pvs[0].moves||'');$('mobileLine').textContent='Best: '+(pvs[0].moves||'');const pct=50+45*(2/Math.PI)*Math.atan(top.whiteScore/3);$('evalFill').style.height=`${Math.max(3,Math.min(97,pct))}%`;drawEngineArrows(pvs)}
function rerenderAppearance(){if(selectedGame)renderAll();const e=$('enginePieceIcon');if(e)e.innerHTML=pieceSvg('b','n')}
window.addEventListener('chessPreference',e=>{if(e.detail?.key==='pieces')rerenderAppearance();if(e.detail?.key==='engine')clearEval()});
$('sync').onclick=()=>sync({automatic:false});$('back').onclick=()=>{$('analysisView').style.display='none';$('libraryView').style.display='block'};$('flip').onclick=()=>{orientation=orientation==='white'?'black':'white';renderAll();const mode=preference('engine','auto'),cached=evalCache.get(mode+'|'+currentChess.fen());if(cached)showEval(cached)};$('analyse').onclick=$('analyseMobile').onclick=analysePosition;$('start').onclick=()=>gotoPly(0);$('prev').onclick=()=>gotoPly(Math.max(0,currentPly-1));$('next').onclick=()=>gotoPly(Math.min(mainMoves.length,currentPly+1));$('end').onclick=()=>gotoPly(mainMoves.length);$('resetVariation').onclick=()=>gotoPly(currentPly);
(async()=>{try{const savedUser=localStorage.getItem('chess-username');if(savedUser)$('user').value=savedUser;const u=$('user').value.trim(),saved=await allGames();renderGames(saved,u);$('status').textContent=saved.length?`Loaded ${saved.length} saved games · checking for new games…`:'No saved games yet · checking Chess.com…';await sync({automatic:true})}catch(e){$('status').textContent='Storage initialisation failed: '+e.message}})();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js');
