import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';

const $=id=>document.getElementById(id);
const PREF='chess-analyser-pref:';
const pref=(k,f)=>localStorage.getItem(PREF+k)||f;
const PROGRESS_KEY='chess-analyser-puzzle-progress-v1';
const DIFFICULTY={beginner:'easier',intermediate:'normal',advanced:'harder',expert:'hardest'};
let queue=[],current=null,chess=new Chess(),orientation='white',selected=null,lastMove=null,solutionIndex=0,initialFen='',attemptMarked=false,failedThisPuzzle=false,solvedThisPuzzle=false,loading=false,awaitingReply=false;

function progress(){try{return JSON.parse(localStorage.getItem(PROGRESS_KEY)||'null')||{attempted:0,solved:0,failed:0,streak:0,bestStreak:0}}catch{return{attempted:0,solved:0,failed:0,streak:0,bestStreak:0}}}
function saveProgress(p){localStorage.setItem(PROGRESS_KEY,JSON.stringify(p));renderProgress()}
function pieceSrc(color,type){const code={p:'P',r:'R',n:'N',b:'B',q:'Q',k:'K'}[type],folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'},folder=folders[pref('pieces','neo')]||folders.neo;return `https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${color}${code}.svg`}
function positionPuzzleTab(){const b=$('puzzlesTab'),ex=$('explorerTab'),analytics=$('analyticsTab');if(!b)return;if(ex&&ex.parentNode){ex.parentNode.insertBefore(b,ex.nextSibling);return}if(analytics?.parentNode)analytics.parentNode.insertBefore(b,analytics)}
function ensureUI(){
  if(!$('puzzleStyles')){const l=document.createElement('link');l.id='puzzleStyles';l.rel='stylesheet';l.href='puzzles.css';document.head.appendChild(l)}
  if(!$('puzzlesTab')){const b=document.createElement('button');b.id='puzzlesTab';b.className='homeTab';b.type='button';b.textContent='Puzzles';const analytics=$('analyticsTab');analytics?.parentNode?.insertBefore(b,analytics)}
  if(!$('puzzlesView')){const s=document.createElement('section');s.id='puzzlesView';s.hidden=true;s.innerHTML=`<div class="topbar"><h1>Puzzles</h1><span class="badge">Lichess puzzle pool</span></div><div class="puzzleShell"><div><div class="boardWrap puzzleBoardWrap"><div class="boardStage"><div id="puzzleBoard" class="board puzzleBoard" aria-label="Puzzle board"></div><div id="puzzleBoardToast" class="puzzleBoardToast" hidden></div></div></div></div><aside class="card puzzlePanel"><h2>Find the best move</h2><p class="muted">Rated tactical positions from the open Lichess puzzle pool.</p><div class="puzzleToolbar"><label>Difficulty<select id="puzzleDifficulty" class="input"><option value="beginner">Beginner</option><option value="intermediate" selected>Intermediate</option><option value="advanced">Advanced</option><option value="expert">Expert</option></select></label><label>Theme<select id="puzzleTheme" class="input"><option value="mix">Mixed</option><option value="fork">Forks</option><option value="pin">Pins</option><option value="mate">Mate</option><option value="sacrifice">Sacrifices</option><option value="endgame">Endgames</option><option value="discoveredAttack">Discovered attacks</option><option value="defensiveMove">Defensive moves</option></select></label></div><div class="puzzleActions"><button id="puzzleHint" class="btn" type="button">Hint</button><button id="puzzleReset" class="btn" type="button">Retry</button><button id="puzzleNext" class="btn primary" type="button">Next puzzle</button></div><div id="puzzleStatus" class="puzzleStatus">Choose a difficulty and start solving.</div><div id="puzzleMeta" class="puzzleMeta"></div><div id="puzzleThemes" class="puzzleThemeTags"></div><div id="puzzleProgress" class="puzzleProgress"></div><div class="puzzleSource">Source: Lichess puzzle API / open puzzle database.</div></aside></div>`;const analytics=$('analyticsView');analytics?.parentNode?.insertBefore(s,analytics)}
  setTimeout(positionPuzzleTab,0)
}
function hideOtherViews(){if($('analysisView'))$('analysisView').style.display='none';if($('libraryView')){$('libraryView').style.display='';$('libraryView').hidden=true}if($('boardLabView'))$('boardLabView').hidden=true;if($('explorerView'))$('explorerView').hidden=true;if($('analyticsView'))$('analyticsView').hidden=true;if($('topPlayersView'))$('topPlayersView').hidden=true}
function showPuzzles(){hideOtherViews();$('puzzlesView').hidden=false;document.querySelectorAll('.homeTab').forEach(x=>x.classList.toggle('active',x.id==='puzzlesTab'));renderBoard();if(!current&&!loading)nextPuzzle()}
function leavePuzzles(){if($('puzzlesView'))$('puzzlesView').hidden=true}
function order(){const files=orientation==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=orientation==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function themeBoard(){const b=$('puzzleBoard');if(!b)return;b.classList.remove('theme-green','theme-brown','theme-blue','theme-grey');b.classList.add('theme-'+pref('board','green'))}
function renderBoard(){const b=$('puzzleBoard');if(!b)return;b.innerHTML='';for(const sq of order()){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(f+r)%2?'dark':'light'}`;el.dataset.square=sq;if(selected===sq)el.classList.add('selected');if(lastMove&&(lastMove.from===sq||lastMove.to===sq))el.classList.add('last');const p=chess.get(sq);if(p){const img=document.createElement('img');img.className='piece';img.src=pieceSrc(p.color,p.type);img.draggable=false;img.alt='';el.appendChild(img)}el.addEventListener('click',()=>tap(sq));b.appendChild(el)}themeBoard()}
function uci(move){return move.from+move.to+(move.promotion||'')}
function legalUci(c,u){if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(u||''))return false;return c.moves({square:u.slice(0,2),verbose:true}).some(m=>m.to===u.slice(2,4)&&(u.length<5||m.promotion===u[4]))}
function setupItem(item){const parsed=new Chess();try{parsed.loadPgn(item.game?.pgn||'')}catch{return false}const moves=parsed.history({verbose:true}),initial=Number(item.puzzle?.initialPly)||0,solution=item.puzzle?.solution||[];for(const count of [initial+1,initial]){try{const c=new Chess();let lm=null;for(let i=0;i<Math.min(count,moves.length);i++)lm=c.move({from:moves[i].from,to:moves[i].to,promotion:moves[i].promotion});if(solution[0]&&legalUci(c,solution[0])){chess=c;lastMove=lm;initialFen=c.fen();orientation=c.turn()==='w'?'white':'black';solutionIndex=0;selected=null;attemptMarked=false;failedThisPuzzle=false;solvedThisPuzzle=false;awaitingReply=false;return true}}catch{}}
  return false
}
function difficultyLabel(){const v=$('puzzleDifficulty')?.value||'intermediate';return v[0].toUpperCase()+v.slice(1)}
async function fetchBatch(){const theme=$('puzzleTheme')?.value||'mix',difficulty=DIFFICULTY[$('puzzleDifficulty')?.value||'intermediate']||'normal',u=`https://lichess.org/api/puzzle/batch/${encodeURIComponent(theme)}?difficulty=${encodeURIComponent(difficulty)}&nb=20`;const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Puzzle service ${r.status}`);const j=await r.json();return Array.isArray(j.puzzles)?j.puzzles:[]}
async function refill(){loading=true;$('puzzleStatus').textContent='Loading puzzles…';try{queue=await fetchBatch();if(!queue.length)throw new Error('No puzzles returned for this filter.')}finally{loading=false}}
function hideToast(){const t=$('puzzleBoardToast');if(t){t.hidden=true;t.className='puzzleBoardToast'}}
function showToast(text,type='success'){const t=$('puzzleBoardToast');if(!t)return;t.textContent=text;t.className=`puzzleBoardToast ${type}`;t.hidden=false}
function scrollToPanel(){if(window.matchMedia('(max-width: 800px)').matches){setTimeout(()=>$('puzzlePanel')?.scrollIntoView({behavior:'smooth',block:'start'}),180)}}
function scrollToBoard(){if(window.matchMedia('(max-width: 800px)').matches){setTimeout(()=>$('puzzleBoard')?.scrollIntoView({behavior:'smooth',block:'center'}),80)}}
async function nextPuzzle(){if(loading)return;try{hideToast();if(!queue.length)await refill();let item=null;while(queue.length&&!item){const x=queue.shift();if(setupItem(x))item=x}if(!item){await refill();while(queue.length&&!item){const x=queue.shift();if(setupItem(x))item=x}}if(!item)throw new Error('Could not prepare a puzzle.');current=item;renderPuzzle();renderBoard();scrollToBoard()}catch(e){current=null;$('puzzleStatus').textContent=`Could not load puzzles: ${e.message}`}}
function renderPuzzle(){if(!current)return;const p=current.puzzle||{};$('puzzleStatus').className='puzzleStatus';$('puzzleStatus').textContent='Your move. Find the best continuation.';$('puzzleMeta').innerHTML=`<span class="puzzleChip">${difficultyLabel()}</span><span class="puzzleChip">Rating ${Number(p.rating)||'—'}</span><span class="puzzleChip">${Number(p.plays||0).toLocaleString()} plays</span>`;$('puzzleThemes').innerHTML=(p.themes||[]).slice(0,6).map(x=>`<span>${String(x).replace(/([A-Z])/g,' $1')}</span>`).join('');renderProgress()}
function markAttempt(){if(attemptMarked)return;attemptMarked=true;const p=progress();p.attempted++;saveProgress(p)}
function markFailed(){if(failedThisPuzzle)return;failedThisPuzzle=true;const p=progress();p.failed++;p.streak=0;saveProgress(p)}
function markSolved(){if(solvedThisPuzzle)return;solvedThisPuzzle=true;const p=progress();p.solved++;p.streak=(p.streak||0)+1;p.bestStreak=Math.max(p.bestStreak||0,p.streak);saveProgress(p)}
function renderProgress(){const p=progress(),root=$('puzzleProgress');if(!root)return;root.innerHTML=`<div><b>${p.solved||0}</b><span>Solved</span></div><div><b>${p.attempted||0}</b><span>Attempted</span></div><div><b>${p.streak||0}</b><span>Streak</span></div><div><b>${p.bestStreak||0}</b><span>Best</span></div>`}
function tap(sq){if(!current||loading||awaitingReply||solvedThisPuzzle)return;if(selected){if(tryMove(selected,sq))return;selected=null}const p=chess.get(sq);if(p&&p.color===chess.turn()){selected=sq;renderBoard()}}
function tryMove(from,to){const opts=chess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!opts.length)return false;const expected=current.puzzle.solution[solutionIndex],candidate=opts.find(m=>uci(m)===expected)||opts[0],played=uci(candidate);markAttempt();if(played!==expected){markFailed();selected=null;$('puzzleStatus').className='puzzleStatus puzzleWrong';$('puzzleStatus').textContent='Not quite. Try another move, or use Hint.';showToast('Not quite — try again','wrong');renderBoard();return true}lastMove=chess.move({from:candidate.from,to:candidate.to,promotion:candidate.promotion});selected=null;solutionIndex++;showToast('Correct ✓','success');renderBoard();advanceSolution();return true}
function finishSolved(){markSolved();awaitingReply=false;$('puzzleStatus').className='puzzleStatus puzzleSolved';$('puzzleStatus').textContent=failedThisPuzzle?'Solved after a retry ✓':'Solved ✓ Great find!';showToast('Puzzle solved ✓','solved');scrollToPanel()}
function advanceSolution(){const solution=current?.puzzle?.solution||[];if(solutionIndex>=solution.length){finishSolved();return}const reply=solution[solutionIndex];awaitingReply=true;$('puzzleStatus').className='puzzleStatus';$('puzzleStatus').textContent='Correct — opponent reply…';setTimeout(()=>{if(!current||!legalUci(chess,reply)){awaitingReply=false;return}lastMove=chess.move({from:reply.slice(0,2),to:reply.slice(2,4),promotion:reply[4]||undefined});solutionIndex++;renderBoard();if(solutionIndex>=solution.length)finishSolved();else{awaitingReply=false;$('puzzleStatus').className='puzzleStatus';$('puzzleStatus').textContent='Good. Keep going — your move.';showToast('Good — keep going','success')}},280)}
function retry(){if(!current||!initialFen)return;if(solvedThisPuzzle){$('puzzleStatus').textContent='This puzzle is already solved. Tap Next puzzle to continue.';scrollToPanel();return}hideToast();chess=new Chess(initialFen);orientation=chess.turn()==='w'?'white':'black';solutionIndex=0;selected=null;lastMove=null;awaitingReply=false;$('puzzleStatus').className='puzzleStatus';$('puzzleStatus').textContent='Try again from the starting position.';renderBoard();scrollToBoard()}
function hint(){if(!current||awaitingReply||solvedThisPuzzle)return;const u=current.puzzle.solution[solutionIndex];if(!u)return;const from=$('puzzleBoard')?.querySelector(`[data-square="${u.slice(0,2)}"]`);from?.classList.add('puzzleSquareHint');$('puzzleStatus').textContent=`Hint: look at the piece on ${u.slice(0,2)}.`;showToast(`Hint: ${u.slice(0,2)}`,'hint');setTimeout(()=>from?.classList.remove('puzzleSquareHint'),1300)}
function filtersChanged(){queue=[];current=null;nextPuzzle()}
function init(){ensureUI();$('puzzlesTab')?.addEventListener('click',showPuzzles);$('puzzleNext')?.addEventListener('click',nextPuzzle);$('puzzleReset')?.addEventListener('click',retry);$('puzzleHint')?.addEventListener('click',hint);$('puzzleDifficulty')?.addEventListener('change',filtersChanged);$('puzzleTheme')?.addEventListener('change',filtersChanged);document.addEventListener('click',e=>{const tab=e.target.closest?.('.homeTab');if(tab&&tab.id!=='puzzlesTab')leavePuzzles()},true);window.addEventListener('chessPreference',e=>{if(e.detail?.key==='pieces'||e.detail?.key==='board')renderBoard()});setTimeout(positionPuzzleTab,20);renderProgress();renderBoard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
