import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { cacheSet,simpleHash,getPositionEval,setPositionEval } from './analysis-store.js';

const $=id=>document.getElementById(id);
const LABELS=['Brilliant','Great','Best','Excellent','Good','Book','Inaccuracy','Mistake','Blunder'];
const GRAPH_COLOR={Brilliant:'#17b89a',Great:'#6d9fc9',Best:'#81b64c',Excellent:'#8fbd62',Good:'#a5a29e',Book:'#c99570',Inaccuracy:'#e1b82f',Mistake:'#e18a3b',Blunder:'#d14b4b'};
const MAX_REFINEMENT_FETCHES=10;
let active=null,token=0,guided=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function ensureCss(){if(document.getElementById('reviewProCss'))return;const l=document.createElement('link');l.id='reviewProCss';l.rel='stylesheet';l.href='review-pro.css';document.head.appendChild(l)}
function moves(){return [...document.querySelectorAll('#moves .move')]}
function sans(){return moves().map(e=>e.childNodes[0]?.textContent?.trim()||e.textContent.trim())}
function key(){return simpleHash(`${$('gameTitle')?.textContent||''}|${sans().join(' ')}`)}
function build(){const c=new Chess(),positions=[c.fen()],ucis=[];for(const san of sans()){try{const m=c.move(san);ucis.push(m.from+m.to+(m.promotion||''));positions.push(c.fen())}catch{return null}}return{positions,ucis}}
function firstMove(s){const u=String(s||'').trim().split(/\s+/)[0];return /^[a-h][1-8][a-h][1-8][qrbn]?$/.test(u)?u:''}
function whitePerspective(raw,fen){const turn=String(fen).split(' ')[1];return turn==='b'?-Number(raw||0):Number(raw||0)}
function terminal(fen){try{const c=new Chess(fen);if(c.isCheckmate())return c.turn()==='w'?-10000:10000;if(c.isDraw()||c.isStalemate()||c.isInsufficientMaterial())return 0}catch{}return null}
function alreadyWhitePerspective(data){return Number(data?.correctionVersion)>=3||/normalized|move-calibrated/i.test(String(data?.accuracyMethod||''))}
async function fetchExact(fen,{allowNetwork=true,allowLive=false}={}){const t=terminal(fen);if(t!==null)return{cp:t,best:'',exact:true,source:'terminal'};const cached=await getPositionEval('cloud',fen).catch(()=>null);if(cached?.pvs?.length){const p=cached.pvs[0],raw=p.mate?((Number(p.mate)>0)?10000:-10000):Number(p.cp)||0;return{cp:whitePerspective(raw,fen),best:firstMove(p.moves),exact:true,source:'cloud-cache'}}
  if(!allowNetwork)return null;
  try{const r=await fetch(`https://lichess.org/api/cloud-eval?fen=${encodeURIComponent(fen)}&multiPv=1&variant=standard`,{headers:{Accept:'application/json'}});if(r.status===429)return null;if(r.ok){const j=await r.json();if(j?.pvs?.length){await setPositionEval('cloud',fen,{source:'Lichess cloud',depth:j.depth||0,pvs:j.pvs.slice(0,1)}).catch(()=>{});const p=j.pvs[0],raw=p.mate?((Number(p.mate)>0)?10000:-10000):Number(p.cp)||0;return{cp:whitePerspective(raw,fen),best:firstMove(p.moves),exact:true,source:'cloud'}}}}catch{}
  if(!allowLive)return null;
  try{const r=await fetch('https://chess-api.com/v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fen,depth:13,variants:1,maxThinkingTime:180})});if(r.ok){const j=await r.json(),raw=j.mate?((Number(j.mate)>0)?10000:-10000):(j.eval!=null?Math.round(Number(j.eval)*100):Number(j.centipawns)||0),best=j.move||j.lan||'';return{cp:whitePerspective(raw,fen),best:/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(best)?best:'',exact:true,source:'live'}}}catch{}
  return null;
}
function cpl(before,after,ply){return Math.max(0,ply%2===1?before-after:after-before)}
function classify(i,ctx,evals,bests,exact){const ply=i+1,loss=cpl(evals[i],evals[i+1],ply),played=ctx.ucis[i],best=bests[i]||'',matched=best&&played===best,verified=exact[i]&&exact[i+1];if(verified&&matched){if(loss<=4&&i>8){const gain=ply%2===1?evals[i+1]-evals[i]:evals[i]-evals[i+1];if(gain>=140)return'Brilliant';if(gain>=65)return'Great'}return'Best'}if(!verified){if(loss>=240)return'Blunder';if(loss>=145)return'Mistake';if(loss>=75)return'Inaccuracy';return'Good'}if(i<10&&loss<=20)return'Book';if(loss<=18)return'Excellent';if(loss<=55)return'Good';if(loss<=120)return'Inaccuracy';if(loss<=230)return'Mistake';return'Blunder'}
function moveAccuracy(loss){const x=Math.max(0,Math.min(1200,Number(loss)||0));return 100/(1+Math.pow(x/150,1.15))}
function accuracy(losses){if(!losses.length)return 100;const scores=losses.map(moveAccuracy),mean=scores.reduce((a,b)=>a+b,0)/scores.length;const mistakes=losses.filter(x=>x>=145&&x<240).length,blunders=losses.filter(x=>x>=240).length;const penalty=Math.min(5,mistakes*.18+blunders*.55);return Math.round(Math.max(0,Math.min(100,mean-penalty))*10)/10}
function graphY(cp,h){const mid=h/2,n=Math.tanh((Number(cp)||0)/360);return mid-n*(h*.38)}
function activateGuidedReview(){guided=true;const v=$('analysisView');if(v){v.classList.add('reviewProMode');v.classList.add('reviewGuidedMode')}decorateReview()}
function resetGuidedReview(){guided=false;active=null;token++;const v=$('analysisView');if(v){v.classList.remove('reviewProMode');v.classList.remove('reviewGuidedMode')}const strip=$('reviewProMoveStrip');if(strip)strip.remove()}
function renderProGraph(data){const root=$('reviewSummaryGraph');if(!root||!data?.evals?.length)return;const w=620,h=126,p=8,n=data.evals.length,x=i=>p+(w-p*2)*(i/Math.max(1,n-1)),y=v=>graphY(v,h),pts=data.evals.map((v,i)=>[x(i),y(v)]),line=pts.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' '),area=`M${pts[0][0].toFixed(1)} ${h-p} `+pts.map(q=>`L${q[0].toFixed(1)} ${q[1].toFixed(1)}`).join(' ')+` L${pts[pts.length-1][0].toFixed(1)} ${h-p} Z`;
  const dots=data.labels.map((label,i)=>{const q=pts[i+1];if(!q)return'';const important=['Brilliant','Great','Inaccuracy','Mistake','Blunder'].includes(label),r=important?5.2:2.4,fill=GRAPH_COLOR[label]||'#aaa';return`<circle class="reviewMoveDot ${important?'important':''}" data-ply="${i+1}" cx="${q[0].toFixed(1)}" cy="${q[1].toFixed(1)}" r="${r}" fill="${fill}"/>`}).join('');
  root.innerHTML=`<svg class="reviewProGraphSvg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Evaluation by move"><line class="reviewGraphZero" x1="${p}" y1="${h/2}" x2="${w-p}" y2="${h/2}"/><path class="reviewGraphArea" d="${area}"/><path class="reviewGraphLine" d="${line}"/>${dots}</svg><div class="reviewGraphLegend"><span>White better</span><span>Tap a dot to open that move</span><span>Black better</span></div>`;
  root.querySelectorAll('[data-ply]').forEach(dot=>dot.addEventListener('click',()=>{const ply=Number(dot.dataset.ply),m=moves()[ply-1];if(!m)return;activateGuidedReview();const screen=$('reviewSummaryScreen');if(screen)screen.hidden=true;m.click();requestAnimationFrame(()=>requestAnimationFrame(()=>$('reviewGuideCard')?.scrollIntoView({behavior:'smooth',block:'start'})))}));
}
function refreshSummary(data){const counts={white:Object.fromEntries(LABELS.map(x=>[x,0])),black:Object.fromEntries(LABELS.map(x=>[x,0]))};data.labels.forEach((x,i)=>counts[i%2===0?'white':'black'][x]++);const b=$('reviewBreakdown');if(b)b.innerHTML=LABELS.map(label=>`<div class="reviewBreakRow"><span class="label">${label}</span><span class="left">${counts.white[label]||0}</span><span class="reviewBreakIcon badge-${label.toLowerCase()}">${({Brilliant:'!!',Great:'!',Best:'★',Excellent:'✓',Good:'✓',Book:'📖',Inaccuracy:'?!',Mistake:'?',Blunder:'??'})[label]}</span><span class="right">${counts.black[label]||0}</span></div>`).join('');const p=$('reviewSummaryPlayers');if(p){const names=($('gameTitle')?.textContent||'White — Black').split(' — ');p.innerHTML=`<div class="reviewSummaryPlayer"><div class="name">${names[0]||'White'}</div><div class="accuracy">${data.whiteAccuracy.toFixed(1)}</div></div><div class="reviewSummaryPlayer"><div class="name">${names[1]||'Black'}</div><div class="accuracy">${data.blackAccuracy.toFixed(1)}</div></div>`}renderProGraph(data)}
function refreshTags(data){moves().forEach((el,i)=>{let t=el.querySelector('.moveTag');if(!t){t=document.createElement('span');el.appendChild(t)}const label=data.labels[i]||'Good';t.className='moveTag tag-'+label.toLowerCase();t.textContent=label;t.title=data.moveVerified[i]?'Engine-verified':'Estimated'})}
function ensureProgress(){const s=$('reviewSummaryScreen');if(!s)return null;let box=$('reviewProLoading');if(box)return box;box=document.createElement('div');box.id='reviewProLoading';box.className='reviewProLoading';box.innerHTML='<span>Polishing review…</span><span id="reviewProPct">0%</span>';const bar=document.createElement('div');bar.className='reviewProProgress';bar.innerHTML='<span></span>';box.after(bar);s.querySelector('.reviewSummaryTop')?.after(box);return box}
function clearProgress(){const x=$('reviewProLoading');if(x)x.remove();document.querySelector('.reviewProProgress')?.remove()}
function setProgress(done,total){if(total<=0){clearProgress();return}ensureProgress();const pct=Math.round(done/Math.max(1,total)*100);if($('reviewProPct'))$('reviewProPct').textContent=pct+'%';document.querySelector('.reviewProProgress>span')?.style.setProperty('width',pct+'%');if(done>=total)setTimeout(clearProgress,250)}
function decorateReview(){const v=$('analysisView');if(v&&guided)v.classList.add('reviewProMode');const c=$('reviewGuideCard');if(c&&!c.querySelector('.reviewProCoach')){const title=c.querySelector('.reviewGuideTitle'),comment=c.querySelector('.reviewGuideComment');const wrap=document.createElement('div');wrap.className='reviewProCoach';wrap.innerHTML='<div class="reviewProCoachFace">♞</div><div class="reviewProCoachText"></div>';const text=wrap.querySelector('.reviewProCoachText');if(title)text.appendChild(title);if(comment)text.appendChild(comment);c.insertBefore(wrap,c.firstChild)}if(guided)ensureMoveStrip()}
function ensureMoveStrip(){if($('reviewProMoveStrip'))return;const side=document.querySelector('#analysisView .sidePanel');if(!side)return;const strip=document.createElement('div');strip.id='reviewProMoveStrip';strip.className='reviewProMoveStrip';side.insertBefore(strip,side.firstChild);renderMoveStrip()}
function renderMoveStrip(){const strip=$('reviewProMoveStrip');if(!strip||!guided)return;strip.innerHTML='';moves().forEach((m,i)=>{const b=document.createElement('button');b.type='button';b.className='reviewProMoveChip';const san=(m.childNodes[0]?.textContent||m.textContent).trim();b.textContent=`${Math.floor(i/2)+1}${i%2?'…':'.'} ${san}`;const lab=active?.labels?.[i];if(['Mistake','Blunder','Inaccuracy'].includes(lab))b.classList.add('bad');else if(['Best','Great','Brilliant'].includes(lab))b.classList.add('good');if(m.classList.contains('active'))b.classList.add('active');b.onclick=()=>m.click();strip.appendChild(b)});const a=strip.querySelector('.active');a?.scrollIntoView({inline:'center',block:'nearest'})}
function normalizedExisting(data,ctx){const normalized=alreadyWhitePerspective(data),out=[];for(let i=0;i<ctx.positions.length;i++){const v=Number(data.evals?.[i]);out[i]=Number.isFinite(v)?(normalized?v:whitePerspective(v,ctx.positions[i])):null}return out}
function refinementTargets(data,ctx,base,exact){const candidates=[];for(let i=0;i<ctx.positions.length;i++){if(exact[i])continue;let priority=0;if(i===0||i===ctx.positions.length-1)priority+=10000;const left=i>0&&base[i-1]!=null&&base[i]!=null?Math.abs(base[i]-base[i-1]):0;const right=i<base.length-1&&base[i]!=null&&base[i+1]!=null?Math.abs(base[i+1]-base[i]):0;priority+=Math.max(left,right);if(i%4===0)priority+=25;candidates.push({i,priority})}return candidates.sort((a,b)=>b.priority-a.priority).slice(0,MAX_REFINEMENT_FETCHES).map(x=>x.i)}
async function refine(detail){const data=detail?.data;if(!data)return;active=data;const ctx=build();if(!ctx)return;const my=++token,n=ctx.positions.length,base=normalizedExisting(data,ctx),evals=[...base],bests=new Array(n).fill(''),exact=new Array(n).fill(false);for(let i=0;i<n;i++){if(data.positionExact?.[i]&&evals[i]!=null){exact[i]=true;bests[i]=data.bestMoves?.[i]||''}const t=terminal(ctx.positions[i]);if(t!==null){evals[i]=t;exact[i]=true;bests[i]=''}}
  const targets=refinementTargets(data,ctx,base,exact);if(!targets.length)clearProgress();for(let k=0;k<targets.length;k++){if(my!==token)return;const i=targets[k],r=await fetchExact(ctx.positions[i],{allowNetwork:true,allowLive:false});if(r){evals[i]=r.cp;bests[i]=r.best;exact[i]=true}setProgress(k+1,targets.length);await sleep(20)}
  for(let i=0;i<n;i++)if(evals[i]==null){let a=i-1,b=i+1;while(a>=0&&evals[a]==null)a--;while(b<n&&evals[b]==null)b++;evals[i]=a>=0&&b<n?Math.round(evals[a]+(evals[b]-evals[a])*(i-a)/(b-a)):a>=0?evals[a]:b<n?evals[b]:0}
  const labels=[],losses=[],wc=[],bc=[];for(let i=0;i<ctx.ucis.length;i++){const loss=cpl(evals[i],evals[i+1],i+1);losses.push(loss);labels.push(classify(i,ctx,evals,bests,exact));(i%2===0?wc:bc).push(loss)}Object.assign(data,{evals,bestMoves:bests,positionExact:exact,moveVerified:labels.map((_,i)=>exact[i]&&exact[i+1]),labels,cpLosses:losses,whiteAccuracy:accuracy(wc),blackAccuracy:accuracy(bc),correctionVersion:6,accuracyMethod:'fast-calibrated-cpl-v6'});active=data;refreshTags(data);refreshSummary(data);if(guided)renderMoveStrip();await cacheSet('review',key(),data).catch(()=>{});window.dispatchEvent(new CustomEvent('reviewNavigation'));}
function init(){ensureCss();window.addEventListener('gameReviewReady',e=>refine(e.detail).catch(()=>{}));window.addEventListener('reviewNavigation',()=>{if(guided){decorateReview();renderMoveStrip()}});document.addEventListener('click',e=>{const t=e.target.closest?.('#reviewStartBtn,#reviewBreakdown .left,#reviewBreakdown .right');if(t){activateGuidedReview();return}if(e.target.closest?.('#runReview')){guided=false;const v=$('analysisView');v?.classList.remove('reviewGuidedMode');v?.classList.remove('reviewProMode')}},true);const title=$('gameTitle');if(title)new MutationObserver(()=>resetGuidedReview()).observe(title,{childList:true,characterData:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
