import { cacheGet,cacheSet,simpleHash } from './analysis-store.js';

const $=id=>document.getElementById(id);
const LABEL_SCORE={Brilliant:100,Great:98,Best:96,Excellent:90,Good:80,Book:98,Inaccuracy:57,Mistake:32,Blunder:8};
const LABEL_COLOR={Brilliant:'#17b89a',Great:'#6d9fc9',Best:'#81b64c',Excellent:'#8fbd62',Good:'#a5a29e',Book:'#c99570',Inaccuracy:'#e1b82f',Mistake:'#e18a3b',Blunder:'#d14b4b'};
let applying=false;

function moveEls(){return [...document.querySelectorAll('#moves .move')]}
function sans(){return moveEls().map(e=>e.childNodes[0]?.textContent?.trim()||e.textContent.trim())}
function reviewKey(){return simpleHash(`${$('gameTitle')?.textContent||''}|${sans().join(' ')}`)}
function winPct(cp){const x=Math.max(-1200,Math.min(1200,Number(cp)||0));return 100/(1+Math.exp(-0.00368208*x))}
function moveWinLoss(before,after,ply){const a=winPct(before),b=winPct(after);return Math.max(0,ply%2===1?a-b:b-a)}
function engineMoveAccuracy(lossPct){const v=103.1668*Math.exp(-0.04354*Math.max(0,lossPct))-3.1668;return Math.max(0,Math.min(100,v))}
function cpLoss(before,after,ply){before=Number(before)||0;after=Number(after)||0;return Math.max(0,ply%2===1?before-after:after-before)}
function perMoveScore(data,i){const label=data.labels?.[i]||'Good',labelScore=LABEL_SCORE[label]??78,before=Number(data.evals?.[i]),after=Number(data.evals?.[i+1]);if(!Number.isFinite(before)||!Number.isFinite(after))return labelScore;const wp=engineMoveAccuracy(moveWinLoss(before,after,i+1)),cpl=cpLoss(before,after,i+1),cpScore=100*Math.exp(-Math.min(900,cpl)/135),verified=!!data.moveVerified?.[i];let score=verified?(.58*wp+.24*cpScore+.18*labelScore):(.32*wp+.28*cpScore+.40*labelScore);if(label==='Mistake')score=Math.min(score,48);if(label==='Blunder')score=Math.min(score,24);if(label==='Inaccuracy')score=Math.min(score,72);return Math.max(1,Math.min(100,score))}
function sideAccuracy(data,side){const values=[];for(let i=side;i<(data.labels?.length||0);i+=2)values.push(perMoveScore(data,i));if(!values.length)return 100;const arithmetic=values.reduce((a,b)=>a+b,0)/values.length;const harmonic=values.length/values.reduce((s,v)=>s+1/Math.max(8,v),0);const geometric=Math.exp(values.reduce((s,v)=>s+Math.log(Math.max(1,v)),0)/values.length);const mistakes=values.filter(v=>v<50&&v>=25).length,blunders=values.filter(v=>v<25).length,inaccuracies=values.filter(v=>v>=50&&v<73).length;const penalty=Math.min(9,blunders*1.6+mistakes*.65+inaccuracies*.16);const score=.50*arithmetic+.30*geometric+.20*harmonic-penalty;return Math.round(Math.max(0,Math.min(100,score))*10)/10}
function updateAccuracyDom(data){const wa=Number(data.whiteAccuracy),ba=Number(data.blackAccuracy);if($('whiteAccuracy'))$('whiteAccuracy').textContent=wa.toFixed(1);if($('blackAccuracy'))$('blackAccuracy').textContent=ba.toFixed(1);const cards=$('reviewSummaryPlayers')?.querySelectorAll('.reviewSummaryPlayer .accuracy');if(cards?.[0])cards[0].textContent=wa.toFixed(1);if(cards?.[1])cards[1].textContent=ba.toFixed(1)}

function ensureBackButton(){const actions=document.querySelector('#reviewGuideCard .reviewGuideActions');if(!actions||$('reviewPrev'))return;const next=$('reviewNext'),b=document.createElement('button');b.id='reviewPrev';b.className='btn reviewPrev';b.type='button';b.innerHTML='← <span>Previous</span>';b.addEventListener('click',()=>{$('prev')?.click();requestAnimationFrame(updateBackState)});actions.insertBefore(b,next||actions.firstChild);updateBackState()}
function updateBackState(){const b=$('reviewPrev');if(!b)return;const els=moveEls(),i=els.findIndex(x=>x.classList.contains('active'));const disabled=i<=0;b.disabled=disabled;b.setAttribute('aria-disabled',String(disabled))}

function graphY(cp,h,pad){const n=Math.tanh((Number(cp)||0)/330);return h/2-n*(h/2-pad)}
function renderChessLikeGraph(data){const root=$('reviewSummaryGraph');if(!root||!Array.isArray(data.evals)||data.evals.length<2)return;const w=680,h=182,padX=14,padY=16,n=data.evals.length,x=i=>padX+(w-padX*2)*(i/Math.max(1,n-1)),pts=data.evals.map((v,i)=>[x(i),graphY(v,h,padY)]);let line='';for(let i=0;i<pts.length;i++){const [px,py]=pts[i];line+=(i?' L':'M')+px.toFixed(1)+' '+py.toFixed(1)}const topArea=`M${pts[0][0].toFixed(1)} ${padY} L${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)} `+pts.slice(1).map(p=>`L${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' ')+` L${pts[pts.length-1][0].toFixed(1)} ${padY} Z`;const bottomArea=`M${pts[0][0].toFixed(1)} ${h-padY} L${pts[0][0].toFixed(1)} ${pts[0][1].toFixed(1)} `+pts.slice(1).map(p=>`L${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' ')+` L${pts[pts.length-1][0].toFixed(1)} ${h-padY} Z`;
  const markers=(data.labels||[]).map((label,i)=>{if(!['Brilliant','Great','Inaccuracy','Mistake','Blunder'].includes(label))return'';const p=pts[i+1];if(!p)return'';return `<circle class="reviewPolishDot" data-ply="${i+1}" cx="${p[0].toFixed(1)}" cy="${p[1].toFixed(1)}" r="5" fill="${LABEL_COLOR[label]}" stroke="#fff" stroke-width="1.6"/>`}).join('');
  const fullMoves=Math.ceil((n-1)/2),step=fullMoves>18?5:fullMoves>9?2:1,ticks=[];for(let m=step;m<=fullMoves;m+=step){const ply=Math.min(n-1,m*2),px=x(ply);ticks.push(`<line x1="${px.toFixed(1)}" y1="${h-padY}" x2="${px.toFixed(1)}" y2="${h-padY+4}" stroke="#777"/><text x="${px.toFixed(1)}" y="${h-1}" text-anchor="middle" fill="#aaa" font-size="10">${m}</text>`)}
  root.innerHTML=`<svg class="reviewProGraphSvg reviewChessGraph" viewBox="0 0 ${w} ${h}" role="img" aria-label="Evaluation by move"><rect x="0" y="0" width="${w}" height="${h}" rx="8" fill="#262522"/><path d="${topArea}" fill="#ecebe8" opacity=".96"/><path d="${bottomArea}" fill="#3d3b38" opacity=".92"/><line x1="${padX}" y1="${h/2}" x2="${w-padX}" y2="${h/2}" stroke="#8b8985" stroke-width="1" opacity=".65"/><path d="${line}" fill="none" stroke="#b9b7b2" stroke-width="2.2" stroke-linejoin="round" stroke-linecap="round"/>${markers}${ticks.join('')}</svg><div class="reviewGraphLegend"><span>White</span><span>Evaluation by move</span><span>Black</span></div>`;
  root.querySelectorAll('.reviewPolishDot').forEach(dot=>dot.addEventListener('click',()=>{const ply=Number(dot.dataset.ply),m=moveEls()[ply-1];if(!m)return;const screen=$('reviewSummaryScreen');if(screen)screen.hidden=true;m.click();requestAnimationFrame(()=>document.querySelector('#reviewGuideCard')?.scrollIntoView({behavior:'smooth',block:'start'}))}))
}

async function polish(){if(applying)return;const k=reviewKey();if(!k)return;const data=await cacheGet('review',k).catch(()=>null);if(!data?.labels?.length)return;if(Number(data.localStockfishVersion)>=20){renderChessLikeGraph(data);ensureBackButton();updateBackState();return;}applying=true;try{const white=sideAccuracy(data,0),black=sideAccuracy(data,1);const changed=Math.abs(Number(data.whiteAccuracy)-white)>.05||Math.abs(Number(data.blackAccuracy)-black)>.05||data.accuracyMethod!=='contextual-calibrated-v8';data.whiteAccuracy=white;data.blackAccuracy=black;data.accuracyMethod='contextual-calibrated-v8';data.correctionVersion=Math.max(8,Number(data.correctionVersion)||0);updateAccuracyDom(data);renderChessLikeGraph(data);ensureBackButton();updateBackState();if(changed)await cacheSet('review',k,data).catch(()=>{})}finally{applying=false}}
function schedule(){clearTimeout(schedule.t);schedule.t=setTimeout(()=>polish().catch(()=>{}),70)}
window.addEventListener('gameReviewReady',schedule);
window.addEventListener('reviewNavigation',schedule);
document.addEventListener('click',e=>{if(e.target.closest?.('#reviewStartBtn,#reviewNext,#reviewPrev,#reviewBreakdown .left,#reviewBreakdown .right,.reviewProMoveChip'))setTimeout(()=>{ensureBackButton();updateBackState();schedule()},0)},true);
new MutationObserver(()=>{if(document.getElementById('reviewGuideCard')){ensureBackButton();updateBackState()}}).observe(document.documentElement,{childList:true,subtree:true});
