import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';

const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser',STORE='games';
let all=[],player='';

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function tag(pgn,name){const m=String(pgn||'').match(new RegExp(`^\\[${name}\\s+"([^"]*)"\\]`,'mi'));return m?m[1]:''}
function titleCase(s){return s.replace(/\b\w/g,c=>c.toUpperCase())}
function opening(g){let name=tag(g.pgn,'Opening'),eco=tag(g.pgn,'ECO');if(!name){const url=tag(g.pgn,'ECOUrl');if(url){let slug=decodeURIComponent(url.split('/').pop()||'').replace(/-\d.*$/,'').replace(/-/g,' ').trim();name=titleCase(slug)}}return{name:name||'Unknown opening',eco}}
function meInfo(g){const u=player.toLowerCase(),white=(g.white?.username||'').toLowerCase()===u,me=white?g.white:g.black,opp=white?g.black:g.white;return{white,me,opp}}
const DRAW=new Set(['agreed','repetition','stalemate','insufficient','50move','timevsinsufficient','draw']);
function outcome(result){return result==='win'?'W':DRAW.has(result)?'D':'L'}
function gameMoves(g){try{const c=new Chess();c.loadPgn(g.pgn||'');return c.history().length}catch{return 0}}
function formatTc(g){if(g.time_class)return g.time_class[0].toUpperCase()+g.time_class.slice(1);const tc=String(g.time_control||'');if(tc.includes('+'))return `${Math.round(Number(tc.split('+')[0])/60)}+${tc.split('+')[1]}`;const n=Number(tc);return Number.isFinite(n)?`${Math.round(n/60)} min`:'Other'}
function cutoff(range){const now=Date.now()/1000;if(range==='30d')return now-30*86400;if(range==='3m')return now-92*86400;if(range==='1y')return now-365*86400;return 0}
function filtered(){const c=cutoff($('analyticsRange').value),tc=$('analyticsTime').value,color=$('analyticsColor').value;return all.filter(g=>(g.end_time||0)>=c&&(tc==='all'||g.time_class===tc)&&(color==='all'||(meInfo(g).white?'white':'black')===color))}
function pct(n,d){return d?Math.round(n*1000/d)/10:0}
function aggregate(items,keyFn){const m=new Map();for(const x of items){const k=keyFn(x);m.set(k,(m.get(k)||0)+1)}return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function record(items){let w=0,d=0,l=0;for(const g of items){const o=outcome(meInfo(g).me?.result);if(o==='W')w++;else if(o==='D')d++;else l++}return{w,d,l,score:pct(w+d*.5,items.length)}}
function streaks(items){const sorted=[...items].sort((a,b)=>(a.end_time||0)-(b.end_time||0));let best=0,worst=0,cw=0,cl=0;for(const g of sorted){const o=outcome(meInfo(g).me?.result);cw=o==='W'?cw+1:0;cl=o==='L'?cl+1:0;best=Math.max(best,cw);worst=Math.max(worst,cl)}return{best,worst}}
function median(a){if(!a.length)return 0;const x=[...a].sort((p,q)=>p-q),i=Math.floor(x.length/2);return x.length%2?x[i]:(x[i-1]+x[i])/2}
function card(label,value,sub=''){return `<div class="analyticsCard"><span>${esc(label)}</span><strong>${esc(value)}</strong>${sub?`<small>${esc(sub)}</small>`:''}</div>`}
function resultBar(r,total){const wp=pct(r.w,total),dp=pct(r.d,total),lp=Math.max(0,100-wp-dp);return `<div class="resultBar" aria-label="${wp}% wins, ${dp}% draws, ${lp}% losses"><i class="win" style="width:${wp}%"></i><i class="draw" style="width:${dp}%"></i><i class="loss" style="width:${lp}%"></i></div><div class="resultLegend"><span>Wins ${r.w} (${wp}%)</span><span>Draws ${r.d} (${dp}%)</span><span>Losses ${r.l} (${lp}%)</span></div>`}
function ratingSvg(items){const pts=[...items].sort((a,b)=>(a.end_time||0)-(b.end_time||0)).map(g=>({x:g.end_time||0,y:Number(meInfo(g).me?.rating)||0})).filter(p=>p.y);if(pts.length<2)return '<div class="analyticsEmpty">Not enough rating data.</div>';const w=720,h=190,p=16,min=Math.min(...pts.map(x=>x.y)),max=Math.max(...pts.map(x=>x.y)),span=Math.max(1,max-min),x=(i)=>p+(w-2*p)*i/(pts.length-1),y=v=>h-p-(h-2*p)*(v-min)/span,path=pts.map((v,i)=>(i?'L':'M')+x(i).toFixed(1)+' '+y(v.y).toFixed(1)).join(' ');return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Rating history"><path d="${path}" class="analyticsLine"/><text x="${p}" y="14">${max}</text><text x="${p}" y="${h-4}">${min}</text></svg>`}
function activity(items){const m=new Map();for(const g of items){const d=new Date((g.end_time||0)*1000),k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;m.set(k,(m.get(k)||0)+1)}const rows=[...m.entries()].sort().slice(-12),max=Math.max(1,...rows.map(x=>x[1]));if(!rows.length)return '<div class="analyticsEmpty">No activity in this period.</div>';return `<div class="activityBars">${rows.map(([k,v])=>`<div class="activityCol"><div class="activityBar" style="height:${Math.max(4,100*v/max)}%" title="${v} games"></div><span>${k.slice(5)}</span><b>${v}</b></div>`).join('')}</div>`}
function table(headers,rows){return `<div class="analyticsTableWrap"><table class="analyticsTable"><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
function openingRows(items){const m=new Map();for(const g of items){const op=opening(g),key=(op.eco?op.eco+' · ':'')+op.name,o=outcome(meInfo(g).me?.result),x=m.get(key)||{n:0,w:0,d:0,l:0};x.n++;x[o.toLowerCase()]++;m.set(key,x)}return [...m.entries()].sort((a,b)=>b[1].n-a[1].n).slice(0,12).map(([k,x])=>`<tr><td>${esc(k)}</td><td>${x.n}</td><td>${x.w}-${x.d}-${x.l}</td><td>${pct(x.w+x.d*.5,x.n)}%</td></tr>`)}
function opponentRows(items){const m=new Map();for(const g of items){const {opp,me}=meInfo(g),k=opp?.username||'Unknown',o=outcome(me?.result),x=m.get(k)||{n:0,w:0,d:0,l:0,ratings:[]};x.n++;x[o.toLowerCase()]++;if(opp?.rating)x.ratings.push(Number(opp.rating));m.set(k,x)}return [...m.entries()].sort((a,b)=>b[1].n-a[1].n).slice(0,12).map(([k,x])=>`<tr><td>${esc(k)}</td><td>${x.n}</td><td>${x.w}-${x.d}-${x.l}</td><td>${pct(x.w+x.d*.5,x.n)}%</td><td>${x.ratings.length?Math.round(x.ratings.reduce((a,b)=>a+b,0)/x.ratings.length):'—'}</td></tr>`)}
function bandRows(items){const bands=[['200+ lower',d=>d>=200],['50–199 lower',d=>d>=50&&d<200],['Similar ±49',d=>d>-50&&d<50],['50–199 higher',d=>d<=-50&&d>-200],['200+ higher',d=>d<=-200]];return bands.map(([name,test])=>{const a=items.filter(g=>{const {me,opp}=meInfo(g);return me?.rating&&opp?.rating&&test(Number(me.rating)-Number(opp.rating))}),r=record(a);return `<tr><td>${name}</td><td>${a.length}</td><td>${r.score}%</td><td>${r.w}-${r.d}-${r.l}</td></tr>`})}
function weekdayRows(items){const names=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];return names.map((name,i)=>{const a=items.filter(g=>new Date((g.end_time||0)*1000).getDay()===i),r=record(a);return `<tr><td>${name}</td><td>${a.length}</td><td>${r.score}%</td></tr>`})}
function terminationRows(items){const a=aggregate(items,g=>meInfo(g).me?.result||'unknown').slice(0,10);return a.map(([k,v])=>`<tr><td>${esc(k.replace(/_/g,' '))}</td><td>${v}</td><td>${pct(v,items.length)}%</td></tr>`)}
function render(){player=(localStorage.getItem('chess-username')||'').trim();const root=$('analyticsContent');if(!player){root.innerHTML='<div class="card analyticsEmpty">Import games for a Chess.com username first.</div>';return}const items=filtered(),r=record(items);if(!items.length){root.innerHTML='<div class="card analyticsEmpty">No games match these filters.</div>';return}const infos=items.map(g=>meInfo(g)),ratings=infos.map(x=>Number(x.me?.rating)).filter(Number.isFinite),oppRatings=infos.map(x=>Number(x.opp?.rating)).filter(Number.isFinite),moves=items.map(gameMoves).filter(Boolean),latest=[...items].sort((a,b)=>(b.end_time||0)-(a.end_time||0))[0],current=Number(meInfo(latest).me?.rating)||0,commonOpening=aggregate(items,g=>opening(g).name)[0],commonOpp=aggregate(items,g=>meInfo(g).opp?.username||'Unknown')[0],tc=aggregate(items,formatTc)[0],st=streaks(items),white=items.filter(g=>meInfo(g).white),black=items.filter(g=>!meInfo(g).white),wr=record(white),br=record(black);
root.innerHTML=`
  <div class="analyticsCards">${card('Games',items.length,`${r.w}W · ${r.d}D · ${r.l}L`)}${card('Score',r.score+'%','win + half draws')}${card('Current rating',current||'—',ratings.length?`high ${Math.max(...ratings)} · low ${Math.min(...ratings)}`:'')}${card('Avg opponent',oppRatings.length?Math.round(oppRatings.reduce((a,b)=>a+b,0)/oppRatings.length):'—',`median ${Math.round(median(oppRatings))||'—'}`)}${card('Most played opening',commonOpening?.[0]||'—',commonOpening?`${commonOpening[1]} games`:'')}${card('Most played opponent',commonOpp?.[0]||'—',commonOpp?`${commonOpp[1]} games`:'')}${card('Avg game length',moves.length?(moves.reduce((a,b)=>a+b,0)/moves.length/2).toFixed(1)+' moves':'—',moves.length?`longest ${Math.ceil(Math.max(...moves)/2)}`:'')}${card('Best win streak',st.best,`longest loss streak ${st.worst}`)}</div>
  <section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Results</h2><span>${items.length} games</span></div>${resultBar(r,items.length)}<div class="analyticsSplit"><div><b>White</b><span>${white.length} games · ${wr.score}% score · ${wr.w}-${wr.d}-${wr.l}</span></div><div><b>Black</b><span>${black.length} games · ${br.score}% score · ${br.w}-${br.d}-${br.l}</span></div><div><b>Most common format</b><span>${esc(tc?.[0]||'—')} · ${tc?.[1]||0} games</span></div></div></section>
  <div class="analyticsGrid2"><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Rating history</h2><span>${current||'—'}</span></div><div class="ratingChart">${ratingSvg(items)}</div></section><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Activity</h2><span>last 12 active months</span></div>${activity(items)}</section></div>
  <section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Openings</h2><span>Most frequently played</span></div>${table(['Opening','Games','W-D-L','Score'],openingRows(items))}</section>
  <section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Opponents</h2><span>Frequent matchups</span></div>${table(['Opponent','Games','W-D-L','Score','Avg rating'],opponentRows(items))}</section>
  <div class="analyticsGrid2"><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Opponent strength</h2><span>Relative to your rating</span></div>${table(['Band','Games','Score','W-D-L'],bandRows(items))}</section><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Day of week</h2><span>When you score best</span></div>${table(['Day','Games','Score'],weekdayRows(items))}</section></div>
  <div class="analyticsGrid2"><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Game endings</h2><span>Chess.com result reason</span></div>${table(['Ending','Games','Share'],terminationRows(items))}</section><section class="analyticsSection card"><div class="analyticsSectionHead"><h2>Quick facts</h2></div><div class="quickFacts"><div><span>Most common time control</span><b>${esc(tc?.[0]||'—')}</b></div><div><span>Highest rating in filter</span><b>${ratings.length?Math.max(...ratings):'—'}</b></div><div><span>Lowest rating in filter</span><b>${ratings.length?Math.min(...ratings):'—'}</b></div><div><span>Games as White / Black</span><b>${white.length} / ${black.length}</b></div></div></section></div>`;
}
async function refresh(){const root=$('analyticsContent');if(root)root.innerHTML='<div class="card analyticsEmpty">Loading analytics…</div>';try{all=await loadGames();render()}catch(e){if(root)root.innerHTML=`<div class="card analyticsEmpty">Could not load analytics: ${esc(e.message)}</div>`}}
function init(){if(!$('analyticsView'))return;for(const id of ['analyticsRange','analyticsTime','analyticsColor'])$(id)?.addEventListener('change',render);window.addEventListener('analyticsTabOpened',refresh);window.addEventListener('storage',e=>{if(e.key==='chess-username')refresh()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
