const DB_NAME='rk93-chess-analyser',STORE='games';
const $=id=>document.getElementById(id);
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'_key'});s.createIndex('end_time','end_time')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putGames(games){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const g of games){g._key=g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`;s.put(g)}tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)})}
async function json(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function archiveDate(url){const m=url.match(/\/(\d{4})\/(\d{2})$/);return m?new Date(+m[1],+m[2]-1,1):new Date(0)}
function filterArchives(archives,range){if(range==='all')return archives;const now=new Date(),cut=new Date(now.getFullYear(),now.getMonth(),1);cut.setMonth(cut.getMonth()-(range==='month'?1:12));return archives.filter(a=>archiveDate(a)>=cut)}
async function rangeImport(){const u=$('user').value.trim();if(!u){$('status').textContent='Enter a Chess.com username first.';return}const range=$('importRange').value,b=$('sync');b.disabled=true;try{localStorage.setItem('chess-username',u);localStorage.setItem('chess-import-range',range);$('status').textContent='Finding Chess.com games…';const data=await json(`https://api.chess.com/pub/player/${encodeURIComponent(u)}/games/archives`);const targets=filterArchives(data.archives||[],range);let count=0;for(let i=0;i<targets.length;i++){$('status').textContent=`Importing ${i+1}/${targets.length} months…`;const month=await json(targets[i]);await putGames(month.games||[]);count+=(month.games||[]).length}$('status').textContent=`Imported ${count} games. Refreshing library…`;setTimeout(()=>location.reload(),350)}catch(e){$('status').textContent='Import failed: '+e.message;b.disabled=false}}
function init(){const user=$('user'),range=$('importRange'),sync=$('sync');const saved=localStorage.getItem('chess-username');if(saved)user.value=saved;const savedRange=localStorage.getItem('chess-import-range');if(savedRange)range.value=savedRange;sync.onclick=e=>{e.preventDefault();e.stopImmediatePropagation();rangeImport()};if(!user.value)$('status').textContent='Enter any Chess.com username and choose how much history to import.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();