import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { cacheGet,cacheSet,simpleHash } from './analysis-store.js';

const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser',STORE='games',PREF='chess-analyser-pref:';
const pref=(k,f)=>localStorage.getItem(PREF+k)||f;
const LICHESS_HOST='https://lichess.org',EXPLORER_HOST='https://explorer.lichess.org';
const OAUTH_CLIENT='rk93.github.io/chess-analyser',TOKEN_KEY='chess-analyser-lichess-token',STATE_KEY='chess-analyser-lichess-state',VERIFIER_KEY='chess-analyser-lichess-verifier';
const INDEX_VERSION=2,MAX_INDEX_PLIES=50;
let chess=new Chess(),orientation='white',selected=null,lastMove=null,moveHistory=[],requestId=0,myRequestId=0,myIndexMemory=null,myIndexStamp='';

function token(){return localStorage.getItem(TOKEN_KEY)||''}
function base64url(bytes){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function randomString(len=48){const a=new Uint8Array(len);crypto.getRandomValues(a);return base64url(a)}
async function sha256(text){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))}
function redirectUri(){const u=new URL(location.href);u.search='';u.hash='';return u.href}
function updateAuthUI(){const b=$('explorerConnect');if(!b)return;if(token()){b.textContent='Lichess connected ✓';b.classList.add('connected');b.title='Tap to disconnect Lichess'}else{b.textContent='Connect Lichess';b.classList.remove('connected');b.title='Required for the global opening database'}}
async function connectLichess(){if(token()){localStorage.removeItem(TOKEN_KEY);updateAuthUI();$('explorerStatus').textContent='Lichess disconnected. Connect again to use the global database.';return}const verifier=randomString(64),state=randomString(24),challenge=base64url(await sha256(verifier));sessionStorage.setItem(VERIFIER_KEY,verifier);sessionStorage.setItem(STATE_KEY,state);const u=new URL(`${LICHESS_HOST}/oauth`);u.searchParams.set('response_type','code');u.searchParams.set('client_id',OAUTH_CLIENT);u.searchParams.set('redirect_uri',redirectUri());u.searchParams.set('code_challenge_method','S256');u.searchParams.set('code_challenge',challenge);u.searchParams.set('state',state);u.searchParams.set('scope','');location.href=u.href}
async function handleOauthReturn(){const u=new URL(location.href),code=u.searchParams.get('code'),state=u.searchParams.get('state');if(!code)return false;const expected=sessionStorage.getItem(STATE_KEY)||'',verifier=sessionStorage.getItem(VERIFIER_KEY)||'',redirect=redirectUri();u.searchParams.delete('code');u.searchParams.delete('state');u.searchParams.delete('scope');window.history.replaceState(null,'',u.href);sessionStorage.removeItem(STATE_KEY);sessionStorage.removeItem(VERIFIER_KEY);if(!state||state!==expected||!verifier)throw new Error('Lichess sign-in could not be verified. Please connect again.');const body=new URLSearchParams({grant_type:'authorization_code',code,redirect_uri:redirect,client_id:OAUTH_CLIENT,code_verifier:verifier});const r=await fetch(`${LICHESS_HOST}/api/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded',Accept:'application/json'},body});if(!r.ok)throw new Error(`Lichess sign-in failed (${r.status})`);const data=await r.json();if(!data.access_token)throw new Error('Lichess did not return an access token.');localStorage.setItem(TOKEN_KEY,data.access_token);return true}

function ensureUI(){if(!$('explorerStyles')){const l=document.createElement('link');l.id='explorerStyles';l.rel='stylesheet';l.href='explorer.css';document.head.appendChild(l)}if(!$('explorerTab')){const b=document.createElement('button');b.id='explorerTab';b.className='homeTab';b.type='button';b.textContent='Explorer';const analytics=$('analyticsTab');analytics?.parentNode?.insertBefore(b,analytics)}if(!$('explorerView')){const s=document.createElement('section');s.id='explorerView';s.hidden=true;s.innerHTML=`<div class="topbar"><h1>Explorer</h1><span class="badge">Global + My games</span></div><div class="explorerShell"><div class="explorerBoardCol"><div class="boardWrap explorerBoardWrap"><div class="boardStage"><div id="explorerBoard" class="board" aria-label="Opening explorer board"></div></div></div></div><aside class="card explorerPanel"><div class="explorerToolbar"><label>Rating pool<select id="explorerRating" class="input"><option value="1000,1200,1400,1600,1800,2000,2200,2500">All ratings</option><option value="1000,1200,1400">1000–1400</option><option value="1600,1800" selected>1600–1800</option><option value="2000,2200,2500">2000+</option></select></label><label>Time controls<select id="explorerSpeed" class="input"><option value="bullet,blitz,rapid,classical">All</option><option value="blitz,rapid" selected>Blitz + Rapid</option><option value="rapid,classical">Rapid + Classical</option><option value="bullet">Bullet</option></select></label></div><div class="explorerActions"><button id="explorerConnect" class="btn primary" type="button">Connect Lichess</button><button id="explorerBack" class="btn" type="button">← Back</button><button id="explorerReset" class="btn" type="button">Starting position</button><button id="explorerFlip" class="btn" type="button">Flip</button></div><div id="explorerStatus" class="explorerStatus">Connect Lichess to load the global database. My Games works without it.</div><div id="explorerHistory" class="explorerHistory">Starting position</div><div id="explorerOpening" class="explorerOpening"></div><div id="explorerTotals" class="explorerTotals"></div><div id="explorerGlobal" class="explorerMoves"></div><div id="explorerMy" class="explorerMy"></div><div id="explorerGames" class="explorerGames"></div></aside></div>`;const analytics=$('analyticsView');analytics?.parentNode?.insertBefore(s,analytics)}updateAuthUI()}
function showExplorer(){const v=$('explorerView');if(!v)return;$('analysisView')?.style.setProperty('display','none');if($('libraryView')){$('libraryView').style.display='';$('libraryView').hidden=true}if($('boardLabView'))$('boardLabView').hidden=true;if($('analyticsView'))$('analyticsView').hidden=true;if($('topPlayersView'))$('topPlayersView').hidden=true;v.hidden=false;document.querySelectorAll('.homeTab').forEach(x=>x.classList.toggle('active',x.id==='explorerTab'));renderBoard();refreshExplorer()}
function leaveExplorer(){if($('explorerView'))$('explorerView').hidden=true}
function pieceSrc(color,type){const code={p:'P',r:'R',n:'N',b:'B',q:'Q',k:'K'}[type],folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'},folder=folders[pref('pieces','neo')]||folders.neo;return `https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${color}${code}.svg`}
function squareOrder(){const files=orientation==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=orientation==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function themeBoard(){const b=$('explorerBoard');if(!b)return;b.classList.remove('theme-green','theme-brown','theme-blue','theme-grey');b.classList.add('theme-'+pref('board','green'))}
function renderBoard(){const b=$('explorerBoard');if(!b)return;b.innerHTML='';for(const sq of squareOrder()){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(f+r)%2?'dark':'light'}`;el.dataset.square=sq;if(selected===sq)el.classList.add('selected');if(lastMove&&(lastMove.from===sq||lastMove.to===sq))el.classList.add('last');const p=chess.get(sq);if(p){const img=document.createElement('img');img.className='piece';img.src=pieceSrc(p.color,p.type);img.draggable=false;img.alt='';el.appendChild(img)}el.addEventListener('click',()=>tapSquare(sq));b.appendChild(el)}themeBoard()}
function tapSquare(sq){if(selected){if(playMove(selected,sq))return;selected=null}const p=chess.get(sq);if(p&&p.color===chess.turn())selected=sq;renderBoard()}
function playMove(from,to,promotion){const legal=chess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!legal.length)return false;const fenBefore=chess.fen(),m=chess.move({from,to,promotion:promotion||(legal.some(x=>x.promotion)?'q':undefined)});if(!m)return false;moveHistory.push({fen:fenBefore,san:m.san});lastMove=m;selected=null;renderBoard();refreshExplorer();return true}
function playUci(uci){if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(uci||''))return;playMove(uci.slice(0,2),uci.slice(2,4),uci[4])}
function reset(){chess=new Chess();moveHistory=[];lastMove=null;selected=null;renderBoard();refreshExplorer()}
function back(){const h=moveHistory.pop();if(!h)return;chess=new Chess(h.fen);lastMove=null;selected=null;renderBoard();refreshExplorer()}
function fenKey(fen){return String(fen).split(' ').slice(0,4).join(' ')}
function historyText(){return moveHistory.length?moveHistory.map((h,i)=>`${i%2===0?Math.floor(i/2)+1+'.':''}${h.san}`).join(' '):'Starting position'}
function ratings(){return $('explorerRating')?.value||'1600,1800'}
function speeds(){return $('explorerSpeed')?.value||'blitz,rapid'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(n,d){return d?Math.round(n*1000/d)/10:0}

async function globalData(fen){const key=`${ratings()}|${speeds()}|${fenKey(fen)}`,cached=await cacheGet('explorer-global',key);if(cached)return cached;const access=token();if(!access)throw Object.assign(new Error('Connect Lichess to use the global database.'),{auth:true});const url=`${EXPLORER_HOST}/lichess?variant=standard&speeds=${encodeURIComponent(speeds())}&ratings=${encodeURIComponent(ratings())}&fen=${encodeURIComponent(fen)}&moves=12&topGames=4&recentGames=0`;const r=await fetch(url,{headers:{Accept:'application/json',Authorization:`Bearer ${access}`}});if(r.status===401){localStorage.removeItem(TOKEN_KEY);updateAuthUI();throw Object.assign(new Error('Lichess connection expired. Tap Connect Lichess and sign in again.'),{auth:true})}if(!r.ok)throw new Error(`Explorer ${r.status}`);const data=await r.json();await cacheSet('explorer-global',key,data);return data}
function renderGlobal(data){const root=$('explorerGlobal'),opening=$('explorerOpening'),total=(data.white||0)+(data.draws||0)+(data.black||0);opening.innerHTML=`<strong>${esc(data.opening?.name||'Position explorer')}</strong><span>${esc(data.opening?.eco||'')} · ${total.toLocaleString()} database games</span>`;$('explorerHistory').textContent=historyText();$('explorerTotals').innerHTML=`<div class="explorerStat"><b>${total.toLocaleString()}</b><span>Games</span></div><div class="explorerStat"><b>${pct(data.white,total)}%</b><span>White wins</span></div><div class="explorerStat"><b>${pct(data.draws,total)}%</b><span>Draws</span></div><div class="explorerStat"><b>${pct(data.black,total)}%</b><span>Black wins</span></div>`;if(!data.moves?.length){root.innerHTML='<div class="explorerStatus">No database moves found from this position.</div>';renderExampleGames(data.topGames||[]);return}root.innerHTML=data.moves.map(m=>{const n=(m.white||0)+(m.draws||0)+(m.black||0);return `<button class="explorerMove" type="button" data-uci="${esc(m.uci)}"><strong>${esc(m.san||m.uci)}</strong><div><div class="explorerMoveMeta">${n.toLocaleString()} games · W ${pct(m.white,n)}% · D ${pct(m.draws,n)}% · B ${pct(m.black,n)}%</div><div class="explorerMoveBar"><i style="width:${Math.max(2,pct(n,total))}%"></i></div></div><div class="explorerMoveRight">${pct(n,total)}%</div></button>`}).join('');root.querySelectorAll('[data-uci]').forEach(b=>b.addEventListener('click',()=>playUci(b.dataset.uci)));renderExampleGames(data.topGames||[])}
function renderExampleGames(games){const root=$('explorerGames');if(!games.length){root.innerHTML='';return}root.innerHTML='<h3>Example games</h3>'+games.slice(0,4).map(g=>{const white=g.players?.white?.name||g.white?.name||g.white||'White',black=g.players?.black?.name||g.black?.name||g.black||'Black',winner=g.winner?`${String(g.winner)[0].toUpperCase()+String(g.winner).slice(1)} won`:'Game';return `<div class="explorerGame"><span>${esc(white)} — ${esc(black)}</span><span>${esc(winner)}</span></div>`}).join('')}

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
function initialFen(pgn){const m=String(pgn||'').match(/^\[FEN\s+"([^"]+)"\]/m);return m?.[1]||null}
function resultCode(pgn){return String(pgn||'').match(/^\[Result\s+"([^"]+)"\]/m)?.[1]||''}
function gameStamp(games,user){return `${INDEX_VERSION}|${user.toLowerCase()}|${games.length}|${Math.max(0,...games.map(g=>Number(g.end_time)||0))}`}
function addIndexPosition(index,key,result,next){let x=index[key];if(!x)x=index[key]={matches:0,w:0,d:0,b:0,moves:{}};x.matches++;if(result==='1-0')x.w++;else if(result==='0-1')x.b++;else x.d++;if(next){const id=next.from+next.to+(next.promotion||''),m=x.moves[id]||(x.moves[id]={san:next.san,uci:id,n:0,w:0,d:0,b:0});m.n++;if(result==='1-0')m.w++;else if(result==='0-1')m.b++;else m.d++}}
async function buildMyIndex(games,user,stamp,tokenId){const index={};for(let i=0;i<games.length;i++){if(tokenId!==myRequestId)return null;const g=games[i];try{const parsed=new Chess();parsed.loadPgn(g.pgn||'');const seq=parsed.history({verbose:true}),c=initialFen(g.pgn)?new Chess(initialFen(g.pgn)):new Chess(),result=resultCode(g.pgn);const limit=Math.min(seq.length,MAX_INDEX_PLIES);for(let j=0;j<=limit;j++){addIndexPosition(index,fenKey(c.fen()),result,j<seq.length?seq[j]:null);if(j<limit)c.move({from:seq[j].from,to:seq[j].to,promotion:seq[j].promotion})}}catch{}if(i%20===19){const root=$('explorerMy');if(root)root.innerHTML=`<h3>My games</h3><div class="explorerStatus">Preparing fast comparison once… ${Math.round((i+1)*100/games.length)}%</div>`;await new Promise(r=>setTimeout(r,0))}}const packed={version:INDEX_VERSION,stamp,positions:index};await cacheSet('explorer-index',simpleHash(stamp),packed);myIndexMemory=packed;myIndexStamp=stamp;return packed}
async function ensureMyIndex(tokenId){const user=(localStorage.getItem('chess-username')||'').trim();if(!user)return null;const games=await loadGames(),stamp=gameStamp(games,user);if(myIndexMemory?.stamp===stamp)return myIndexMemory;const cached=await cacheGet('explorer-index',simpleHash(stamp));if(cached?.version===INDEX_VERSION&&cached.stamp===stamp){myIndexMemory=cached;myIndexStamp=stamp;return cached}return buildMyIndex(games,user,stamp,tokenId)}
async function myPositionData(fen,tokenId){const idx=await ensureMyIndex(tokenId);if(!idx||tokenId!==myRequestId)return null;const x=idx.positions?.[fenKey(fen)];if(!x)return{matches:0,w:0,d:0,b:0,moves:[]};return{matches:x.matches,w:x.w,d:x.d,b:x.b,moves:Object.values(x.moves||{}).sort((a,z)=>z.n-a.n).slice(0,10)}}
function renderMy(data){const root=$('explorerMy');if(!data){root.innerHTML='<h3>My games</h3><div class="explorerStatus">Import your Chess.com games to compare your choices with the global database.</div>';return}if(!data.matches){root.innerHTML=`<h3>My games</h3><div class="explorerStatus">This position was not found in the indexed first ${MAX_INDEX_PLIES/2} moves of your imported games.</div>`;return}root.innerHTML=`<h3>My games · ${data.matches} position matches</h3><div class="explorerStatus">White ${pct(data.w,data.matches)}% · Draw ${pct(data.d,data.matches)}% · Black ${pct(data.b,data.matches)}%</div>${data.moves.map(m=>`<div class="explorerMyRow"><b>${esc(m.san)}</b><span>${m.n} game${m.n===1?'':'s'}</span><span>${pct(m.n,data.matches)}%</span></div>`).join('')}`}

async function refreshExplorer(){const id=++requestId,myId=++myRequestId,fen=chess.fen();$('explorerHistory').textContent=historyText();$('explorerGlobal').innerHTML='';$('explorerMy').innerHTML='<h3>My games</h3><div class="explorerStatus">Loading saved comparison index…</div>';if(token())$('explorerStatus').textContent='Loading global database…';else $('explorerStatus').textContent='Connect Lichess for global data. Loading My Games locally…';try{const data=await globalData(fen);if(id!==requestId)return;renderGlobal(data);$('explorerStatus').textContent='Global database loaded.'}catch(e){if(id===requestId){$('explorerStatus').textContent=e.auth?e.message:`Could not load global explorer: ${e.message}`;if(e.auth)$('explorerGlobal').innerHTML='<div class="explorerStatus">Global results need a Lichess connection. My Games below works locally.</div>'}}try{const mine=await myPositionData(fen,myId);if(myId===myRequestId)renderMy(mine)}catch(e){if(myId===myRequestId)$('explorerMy').innerHTML=`<h3>My games</h3><div class="explorerStatus">Could not prepare your saved-game comparison: ${esc(e.message)}</div>`}}
async function init(){ensureUI();try{if(await handleOauthReturn()){$('explorerStatus').textContent='Lichess connected. Open Explorer to load global data.'}}catch(e){$('explorerStatus').textContent=e.message}updateAuthUI();$('explorerConnect')?.addEventListener('click',connectLichess);$('explorerTab')?.addEventListener('click',showExplorer);['gamesTab','boardLabTab','analyticsTab','topPlayersTab'].forEach(id=>$(id)?.addEventListener('click',leaveExplorer));$('explorerReset')?.addEventListener('click',reset);$('explorerBack')?.addEventListener('click',back);$('explorerFlip')?.addEventListener('click',()=>{orientation=orientation==='white'?'black':'white';renderBoard()});$('explorerRating')?.addEventListener('change',refreshExplorer);$('explorerSpeed')?.addEventListener('change',refreshExplorer);window.addEventListener('chessPreference',e=>{if(e.detail?.key==='pieces'||e.detail?.key==='board')renderBoard()});renderBoard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
