import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { cacheGet,cacheSet,simpleHash } from './analysis-store.js';

const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser',STORE='games',PREF='chess-analyser-pref:';
const pref=(k,f)=>localStorage.getItem(PREF+k)||f;
let chess=new Chess(),orientation='white',selected=null,lastMove=null,history=[],requestId=0,myRequestId=0;

function pieceSrc(color,type){const code={p:'P',r:'R',n:'N',b:'B',q:'Q',k:'K'}[type],folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'},folder=folders[pref('pieces','neo')]||folders.neo;return `https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${color}${code}.svg`}
function squareOrder(){const files=orientation==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=orientation==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function themeBoard(){const b=$('explorerBoard');if(!b)return;b.classList.remove('theme-green','theme-brown','theme-blue','theme-grey');b.classList.add('theme-'+pref('board','green'))}
function renderBoard(){const b=$('explorerBoard');if(!b)return;b.innerHTML='';for(const sq of squareOrder()){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(f+r)%2?'dark':'light'}`;el.dataset.square=sq;if(selected===sq)el.classList.add('selected');if(lastMove&&(lastMove.from===sq||lastMove.to===sq))el.classList.add('last');const p=chess.get(sq);if(p){const img=document.createElement('img');img.className='piece';img.src=pieceSrc(p.color,p.type);img.draggable=false;img.alt='';el.appendChild(img)}el.addEventListener('click',()=>tapSquare(sq));b.appendChild(el)}themeBoard()}
function tapSquare(sq){if(selected){if(playMove(selected,sq))return;selected=null}const p=chess.get(sq);if(p&&p.color===chess.turn())selected=sq;renderBoard()}
function playMove(from,to,promotion){const legal=chess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!legal.length)return false;const fenBefore=chess.fen(),m=chess.move({from,to,promotion:promotion||(legal.some(x=>x.promotion)?'q':undefined)});if(!m)return false;history.push({fen:fenBefore,san:m.san});lastMove=m;selected=null;renderBoard();refreshExplorer();return true}
function playUci(uci){if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(uci||''))return;playMove(uci.slice(0,2),uci.slice(2,4),uci[4])}
function reset(){chess=new Chess();history=[];lastMove=null;selected=null;renderBoard();refreshExplorer()}
function back(){const h=history.pop();if(!h)return;chess=new Chess(h.fen);lastMove=null;selected=null;renderBoard();refreshExplorer()}
function fenKey(fen){return String(fen).split(' ').slice(0,4).join(' ')}
function historyText(){return history.length?history.map((h,i)=>`${i%2===0?Math.floor(i/2)+1+'.':''}${h.san}`).join(' '):'Starting position'}
function ratings(){const v=$('explorerRating')?.value||'1600,1800,2000,2200,2500';return v}
function speeds(){return $('explorerSpeed')?.value||'blitz,rapid,classical'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(n,d){return d?Math.round(n*1000/d)/10:0}

async function globalData(fen){const key=`${ratings()}|${speeds()}|${fenKey(fen)}`,cached=await cacheGet('explorer-global',key);if(cached)return cached;const url=`https://explorer.lichess.ovh/lichess?variant=standard&speeds=${encodeURIComponent(speeds())}&ratings=${encodeURIComponent(ratings())}&fen=${encodeURIComponent(fen)}&moves=12&topGames=4&recentGames=0`;const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Explorer ${r.status}`);const data=await r.json();await cacheSet('explorer-global',key,data);return data}
function renderGlobal(data){const root=$('explorerGlobal'),opening=$('explorerOpening'),total=(data.white||0)+(data.draws||0)+(data.black||0);opening.innerHTML=`<strong>${esc(data.opening?.name||'Position explorer')}</strong><span>${esc(data.opening?.eco||'')} · ${total.toLocaleString()} database games</span>`;$('explorerHistory').textContent=historyText();$('explorerTotals').innerHTML=`<div class="explorerStat"><b>${total.toLocaleString()}</b><span>Games</span></div><div class="explorerStat"><b>${pct(data.white,total)}%</b><span>White wins</span></div><div class="explorerStat"><b>${pct(data.draws,total)}%</b><span>Draws</span></div><div class="explorerStat"><b>${pct(data.black,total)}%</b><span>Black wins</span></div>`;if(!data.moves?.length){root.innerHTML='<div class="explorerStatus">No database moves found from this position.</div>';return}root.innerHTML=data.moves.map(m=>{const n=(m.white||0)+(m.draws||0)+(m.black||0);return `<button class="explorerMove" type="button" data-uci="${esc(m.uci)}"><strong>${esc(m.san||m.uci)}</strong><div><div class="explorerMoveMeta">${n.toLocaleString()} games · W ${pct(m.white,n)}% · D ${pct(m.draws,n)}% · B ${pct(m.black,n)}%</div><div class="explorerMoveBar"><i style="width:${Math.max(2,pct(n,total))}%"></i></div></div><div class="explorerMoveRight">${pct(n,total)}%</div></button>`}).join('');root.querySelectorAll('[data-uci]').forEach(b=>b.addEventListener('click',()=>playUci(b.dataset.uci)));renderExampleGames(data.topGames||[])}
function renderExampleGames(games){const root=$('explorerGames');if(!games.length){root.innerHTML='';return}root.innerHTML='<h3>Example games</h3>'+games.slice(0,4).map(g=>{const white=g.players?.white?.name||g.white?.name||g.white||'White',black=g.players?.black?.name||g.black?.name||g.black||'Black',winner=g.winner?`${String(g.winner)[0].toUpperCase()+String(g.winner).slice(1)} won`:'Result available';return `<div class="explorerGame"><span>${esc(white)} — ${esc(black)}</span><span>${esc(winner)}</span></div>`}).join('')}

function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function loadGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
function initialFen(pgn){const m=String(pgn||'').match(/^\[FEN\s+"([^"]+)"\]/m);return m?.[1]||null}
async function myPositionData(fen,token){const user=(localStorage.getItem('chess-username')||'').trim();if(!user)return null;const games=await loadGames(),stamp=`${games.length}|${Math.max(0,...games.map(g=>Number(g.end_time)||0))}`,key=`${user.toLowerCase()}|${stamp}|${fenKey(fen)}`,cached=await cacheGet('explorer-my',simpleHash(key));if(cached)return cached;const target=fenKey(fen),moves=new Map();let matches=0,w=0,d=0,b=0;for(let i=0;i<games.length;i++){if(token!==myRequestId)return null;const g=games[i];try{const parsed=new Chess();parsed.loadPgn(g.pgn||'');const seq=parsed.history({verbose:true}),c=initialFen(g.pgn)?new Chess(initialFen(g.pgn)):new Chess();for(let j=0;j<=seq.length;j++){if(fenKey(c.fen())===target){matches++;const result=String(g.pgn||'').match(/^\[Result\s+"([^"]+)"\]/m)?.[1]||'';if(result==='1-0')w++;else if(result==='0-1')b++;else d++;if(j<seq.length){const m=seq[j],x=moves.get(m.san)||{san:m.san,uci:m.from+m.to+(m.promotion||''),n:0,w:0,d:0,b:0};x.n++;if(result==='1-0')x.w++;else if(result==='0-1')x.b++;else x.d++;moves.set(m.san,x)}break}if(j<seq.length)c.move({from:seq[j].from,to:seq[j].to,promotion:seq[j].promotion})}}catch{}if(i%30===29)await new Promise(r=>setTimeout(r,0))}const data={matches,w,d,b,moves:[...moves.values()].sort((a,z)=>z.n-a.n).slice(0,10)};await cacheSet('explorer-my',simpleHash(key),data);return data}
function renderMy(data){const root=$('explorerMy');if(!data){root.innerHTML='<h3>My games</h3><div class="explorerStatus">Import your Chess.com games to compare your choices with the global database.</div>';return}if(!data.matches){root.innerHTML='<h3>My games</h3><div class="explorerStatus">This position has not appeared in your imported games.</div>';return}root.innerHTML=`<h3>My games · ${data.matches} position matches</h3><div class="explorerStatus">White ${pct(data.w,data.matches)}% · Draw ${pct(data.d,data.matches)}% · Black ${pct(data.b,data.matches)}%</div>${data.moves.map(m=>`<div class="explorerMyRow"><b>${esc(m.san)}</b><span>${m.n} game${m.n===1?'':'s'}</span><span>${pct(m.n,data.matches)}%</span></div>`).join('')}`}

async function refreshExplorer(){const id=++requestId,myId=++myRequestId,fen=chess.fen();$('explorerStatus').textContent='Loading global database…';$('explorerGlobal').innerHTML='';$('explorerMy').innerHTML='<h3>My games</h3><div class="explorerStatus">Comparing your imported games…</div>';try{const data=await globalData(fen);if(id!==requestId)return;renderGlobal(data);$('explorerStatus').textContent='Global database loaded.'}catch(e){if(id===requestId)$('explorerStatus').textContent='Could not load global explorer: '+e.message}try{const mine=await myPositionData(fen,myId);if(myId===myRequestId)renderMy(mine)}catch{if(myId===myRequestId)$('explorerMy').innerHTML='<h3>My games</h3><div class="explorerStatus">Could not compare your saved games.</div>'}}
function init(){if(!$('explorerView'))return;$('explorerReset').addEventListener('click',reset);$('explorerBack').addEventListener('click',back);$('explorerFlip').addEventListener('click',()=>{orientation=orientation==='white'?'black':'white';renderBoard()});$('explorerRating').addEventListener('change',refreshExplorer);$('explorerSpeed').addEventListener('change',refreshExplorer);window.addEventListener('explorerTabOpened',()=>{renderBoard();refreshExplorer()});window.addEventListener('chessPreference',e=>{if(e.detail?.key==='pieces'||e.detail?.key==='board')renderBoard()});renderBoard()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
