import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { cacheGet,cacheSet,getPositionEval,setPositionEval,simpleHash } from './analysis-store.js';

const $=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const REVIEW_VERSION=3;
const CLOUD_CONCURRENCY=3;
const LIVE_FALLBACK_LIMIT=6;
let running=false,reviewToken=0,restoreTimer=null;

function moveEls(){return [...document.querySelectorAll('#moves .move')]}
function moveSans(){return moveEls().map(e=>e.childNodes[0]?.textContent?.trim()||e.textContent.trim())}
function buildPositions(){const c=new Chess(),out=[{fen:c.fen(),ply:0}];for(const san of moveSans()){try{c.move(san);out.push({fen:c.fen(),ply:out.length})}catch{return []}}return out}
function cpFromPv(pv){if(pv?.mate!==undefined&&pv?.mate!==null&&Number(pv.mate)!==0)return Number(pv.mate)>0?10000:-10000;return Number(pv?.cp)||0}
function firstMove(moves){const u=String(moves||'').trim().split(/\s+/)[0];return /^[a-h][1-8][a-h][1-8][qrbn]?$/.test(u)?u:''}
function sanForUci(fen,uci){if(!uci)return'';try{const c=new Chess(fen),m=c.move({from:uci.slice(0,2),to:uci.slice(2,4),promotion:uci[4]||undefined});return m?.san||uci}catch{return uci}}
function reviewKey(){return simpleHash(`${$('gameTitle')?.textContent||''}|${moveSans().join(' ')}`)}
function canonical(data){return data?.pvs?.length?data:null}
function signalRunning(value){window.dispatchEvent(new CustomEvent('gameReviewRunning',{detail:{running:value}}))}
async function cloudEval(fen){let data=canonical(await getPositionEval('cloud',fen));if(!data){const r=await fetch(`https://lichess.org/api/cloud-eval?fen=${encodeURIComponent(fen)}&multiPv=3&variant=standard`,{headers:{Accept:'application/json'}});if(r.status===404)return null;if(!r.ok)throw new Error(`Cloud ${r.status}`);const j=await r.json();if(!j.pvs?.length)return null;data={source:'Lichess cloud',depth:j.depth||0,pvs:j.pvs.slice(0,3)};await setPositionEval('cloud',fen,data)}const pv=data.pvs[0];return{cp:cpFromPv(pv),best:firstMove(pv.moves),depth:data.depth||0,source:'cloud'}}
async function liveEval(fen){let data=canonical(await getPositionEval('live',fen));if(!data){const r=await fetch('https://chess-api.com/v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fen,depth:14,variants:1,maxThinkingTime:180})});if(!r.ok)throw new Error(`Live ${r.status}`);const j=await r.json(),best=j.move||j.lan||'',cont=Array.isArray(j.continuationArr)?j.continuationArr.filter(Boolean):[],moves=[best,...cont.filter((m,i)=>!(i===0&&m===best))].filter(Boolean).join(' '),cp=j.eval!=null?Math.round(Number(j.eval)*100):Number(j.centipawns)||0;data={source:'Stockfish live',depth:j.depth||14,pvs:[{cp,mate:j.mate,moves}]};await setPositionEval('live',fen,data)}const pv=data.pvs[0];return{cp:cpFromPv(pv),best:firstMove(pv.moves),depth:data.depth||14,source:'live'}}
function winProb(cp){const pawns=Math.max(-10,Math.min(10,cp/100));return 1/(1+Math.exp(-1.25*pawns))}
function moveLoss(before,after,ply){const wb=winProb(before),wa=winProb(after);return Math.max(0,ply%2===1?wb-wa:wa-wb)}
function classify(loss){if(loss<=.004)return'Best';if(loss<=.014)return'Excellent';if(loss<=.04)return'Good';if(loss<=.09)return'Inaccuracy';if(loss<=.18)return'Mistake';return'Blunder'}
function accuracy(losses){if(!losses.length)return 100;const scores=losses.map(l=>100*Math.exp(-4.2*l));return Math.round(Math.max(0,Math.min(100,scores.reduce((a,b)=>a+b,0)/scores.length))*10)/10}
function interpolate(evals){for(let i=0;i<evals.length;i++){if(evals[i]!=null)continue;let a=i-1,b=i+1;while(a>=0&&evals[a]==null)a--;while(b<evals.length&&evals[b]==null)b++;if(a>=0&&b<evals.length)evals[i]=Math.round(evals[a]+(evals[b]-evals[a])*(i-a)/(b-a));else if(a>=0)evals[i]=evals[a];else if(b<evals.length)evals[i]=evals[b];else evals[i]=0}}
function clearTags(){document.querySelectorAll('#moves .moveTag,#moves .practiceMove').forEach(e=>e.remove())}
function launchPractice(e,detail){e.preventDefault();e.stopPropagation();window.dispatchEvent(new CustomEvent('practiceMistake',{detail}))}
function renderTags(labels,positions,bestMoves,sans){clearTags();const els=moveEls();labels.forEach((label,i)=>{if(!els[i])return;const tag=document.createElement('span');tag.className='moveTag tag-'+label.toLowerCase();tag.textContent=label;els[i].appendChild(tag);if((label!=='Mistake'&&label!=='Blunder')||!bestMoves[i])return;const before=positions[i]?.fen,best=bestMoves[i],btn=document.createElement('button');btn.type='button';btn.className='practiceMove';btn.textContent='Practice';btn.title=`Practice the position before ${sans[i]||'this move'}`;btn.addEventListener('click',e=>launchPractice(e,{fen:before,badMove:sans[i]||'',label,ply:i+1,moveNumber:Math.floor(i/2)+1,side:i%2===0?'White':'Black',bestMove:best,bestSan:sanForUci(before,best)}));els[i].appendChild(btn)})}
function renderSummary(labels){const order=['Best','Excellent','Good','Inaccuracy','Mistake','Blunder'],counts=Object.fromEntries(order.map(k=>[k,0]));labels.forEach(x=>counts[x]++);$('reviewSummary').innerHTML=order.map(k=>`<span class="reviewCount ${'tag-'+k.toLowerCase()}"><b>${counts[k]}</b> ${k}</span>`).join('')}
function renderGraph(evals,losses){const root=$('reviewGraph'),w=620,h=180,pad=12,clamp=v=>Math.max(-600,Math.min(600,v)),xs=i=>pad+(w-pad*2)*(i/Math.max(1,evals.length-1)),ys=v=>h/2-(clamp(v)/600)*(h/2-pad);let path='';evals.forEach((v,i)=>{path+=(i?' L':'M')+xs(i).toFixed(1)+' '+ys(v).toFixed(1)});let maxIdx=1,maxLoss=-1;losses.forEach((l,i)=>{if(l>maxLoss){maxLoss=l;maxIdx=i+1}});const mx=xs(maxIdx),my=ys(evals[maxIdx]||0);root.innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Evaluation graph"><line x1="${pad}" y1="${h/2}" x2="${w-pad}" y2="${h/2}" class="reviewZero"/><path d="${path}" class="reviewLine"/><circle cx="${mx}" cy="${my}" r="6" class="reviewSwing"/></svg><div class="reviewGraphCaption">Largest evaluation swing: move ${Math.ceil(maxIdx/2)}${maxIdx%2?'…':''}</div>`;root.hidden=false}
function displayReview(data,{cached=false}={}){const positions=buildPositions(),sans=moveSans();if(positions.length!==data.evals.length||sans.length!==data.labels.length)return false;$('whiteAccuracy').textContent=Number(data.whiteAccuracy).toFixed(1);$('blackAccuracy').textContent=Number(data.blackAccuracy).toFixed(1);$('accuracyCards').hidden=false;renderTags(data.labels,positions,data.bestMoves||[],sans);renderSummary(data.labels);renderGraph(data.evals,data.losses);const trainable=(data.bestMoves||[]).filter((m,i)=>m&&(data.labels[i]==='Mistake'||data.labels[i]==='Blunder')).length;$('reviewStatus').textContent=cached?`Saved review loaded · ${trainable} practice position${trainable===1?'':'s'} ready.`:`Review complete · ${trainable} verified practice position${trainable===1?'':'s'} ready.`;return true}
async function restoreReview(){clearTimeout(restoreTimer);restoreTimer=setTimeout(async()=>{const sans=moveSans();if(!sans.length)return;const key=reviewKey(),data=await cacheGet('review',key);if(data?.version===REVIEW_VERSION)displayReview(data,{cached:true})},120)}
async function runCloudPool(positions,evals,bestMoves,token){let next=0,done=0,cloudUsed=0;async function worker(){while(true){const i=next++;if(i>=positions.length||token!==reviewToken)return;let e=null;try{e=await cloudEval(positions[i].fen)}catch{}if(e){evals[i]=e.cp;bestMoves[i]=e.best||'';cloudUsed++}done++;$('reviewStatus').textContent=`Fast cloud pass ${done}/${positions.length}…`;if(done%9===0)await sleep(40)}}await Promise.all(Array.from({length:Math.min(CLOUD_CONCURRENCY,positions.length)},worker));return cloudUsed}
function missingFallbackIndexes(evals){const missing=[];for(let i=0;i<evals.length;i++)if(evals[i]==null)missing.push(i);if(missing.length<=LIVE_FALLBACK_LIMIT)return missing;const out=[];for(let n=0;n<LIVE_FALLBACK_LIMIT;n++)out.push(missing[Math.round(n*(missing.length-1)/(LIVE_FALLBACK_LIMIT-1))]);return [...new Set(out)]}
async function runReview(){if(running)return;const positions=buildPositions(),sans=moveSans();if(positions.length<2){$('reviewStatus').textContent='Open a game with moves before running Game Review.';return}const key=reviewKey(),saved=await cacheGet('review',key);if(saved?.version===REVIEW_VERSION&&displayReview(saved,{cached:true}))return;running=true;signalRunning(true);const token=++reviewToken,btn=$('runReview');btn.disabled=true;btn.textContent='Reviewing…';clearTags();$('reviewSummary').innerHTML='';$('accuracyCards').hidden=true;$('reviewGraph').hidden=true;const evals=new Array(positions.length).fill(null),bestMoves=new Array(positions.length).fill('');let liveUsed=0,cloudUsed=0;
try{cloudUsed=await runCloudPool(positions,evals,bestMoves,token);if(token!==reviewToken)return;const fallback=missingFallbackIndexes(evals);for(let n=0;n<fallback.length;n++){if(token!==reviewToken)return;const i=fallback[n];$('reviewStatus').textContent=`Filling uncached positions ${n+1}/${fallback.length}…`;let e=null;try{e=await liveEval(positions[i].fen)}catch{}if(e){evals[i]=e.cp;bestMoves[i]=e.best||'';liveUsed++}if(n<fallback.length-1)await sleep(60)}interpolate(evals);const losses=[],labels=[],whiteLoss=[],blackLoss=[];for(let ply=1;ply<evals.length;ply++){const loss=moveLoss(evals[ply-1],evals[ply],ply);losses.push(loss);labels.push(classify(loss));(ply%2?whiteLoss:blackLoss).push(loss)}const data={version:REVIEW_VERSION,evals,losses,labels,bestMoves,whiteAccuracy:accuracy(whiteLoss),blackAccuracy:accuracy(blackLoss),cloudUsed,liveUsed,updated:Date.now()};await cacheSet('review',key,data);displayReview(data)}catch(e){$('reviewStatus').textContent='Game Review failed: '+e.message}finally{running=false;signalRunning(false);btn.disabled=false;btn.textContent='Review game'}}
function resetReviewUI(){reviewToken++;if(running)signalRunning(false);running=false;clearTags();$('reviewSummary').innerHTML='';$('accuracyCards').hidden=true;$('reviewGraph').hidden=true;$('reviewStatus').textContent='Analyse the whole game for accuracy, move quality and evaluation swings.';restoreReview()}
function init(){const b=$('runReview');if(b)b.addEventListener('click',runReview);const title=$('gameTitle');if(title)new MutationObserver(resetReviewUI).observe(title,{childList:true,characterData:true,subtree:true});restoreReview()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
