const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser',STORE='games';
let running=false;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'_key'});s.createIndex('end_time','end_time')}};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putGames(games){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const g of games){g._key=g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`;s.put(g)}tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function allGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
async function getJSON(url,ms=15000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{Accept:'application/json'},signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}
async function getJSONRetry(url,attempts=3){let last;for(let i=0;i<attempts;i++){try{return await getJSON(url)}catch(e){last=e;if(i<attempts-1)await sleep(500*(i+1))}}throw last}
function key(g){return g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`}
function pickArchives(archives,range){if(range==='all')return [...archives];if(range==='year')return archives.slice(-12);return archives.slice(-1)}
function renderFallback(games,u){const root=$('games');if(!root)return;const mine=games.filter(g=>g.white?.username?.toLowerCase()===u.toLowerCase()||g.black?.username?.toLowerCase()===u.toLowerCase()).sort((a,b)=>(b.end_time||0)-(a.end_time||0));root.innerHTML='';if(!mine.length){root.innerHTML='<div class="game">No saved games yet.</div>';return}for(const g of mine){const isWhite=g.white.username.toLowerCase()===u.toLowerCase(),me=isWhite?g.white:g.black,opp=isWhite?g.black:g.white,d=document.createElement('div');d.className='game';d.innerHTML=`<b>${me.username} ${me.rating??''}</b> — ${opp.username} ${opp.rating??''}<div class="muted">${new Date((g.end_time||0)*1000).toLocaleString()}</div>`;root.appendChild(d)}}
function collapseImportAfterSuccess(){const top=document.querySelector('#libraryView > .topbar'),sync=document.querySelector('#libraryView > .syncCard');top?.classList.add('uxCollapsed');sync?.classList.add('uxCollapsed');top?.classList.remove('uxRevealed');sync?.classList.remove('uxRevealed');window.dispatchEvent(new CustomEvent('chessImportFinished'))}
async function robustImport({compact=false}={}){if(running)return;const button=$('sync'),status=$('status'),user=$('user'),range=$('importRange');if(!button||!user)return;const saved=localStorage.getItem('chess-username')||'',u=(user.value||saved).trim();if(!u){status.textContent='Enter a Chess.com username';document.querySelector('#libraryView > .syncCard')?.classList.add('uxRevealed');return}user.value=u;running=true;button.disabled=true;button.textContent='Importing…';localStorage.setItem('chess-username',u);try{status.textContent=compact?'Checking complete Chess.com history…':'Finding Chess.com archives…';const a=await getJSONRetry(`https://api.chess.com/pub/player/${encodeURIComponent(u)}/games/archives`);const selectedRange=compact?'all':(range?.value||'month');const targets=pickArchives(a.archives||[],selectedRange);if(!targets.length)throw new Error('No Chess.com game archives found for this user');const before=await allGames(),existing=new Set(before.map(key));let newCount=0,failed=0,loadedGames=0;for(let i=0;i<targets.length;i++){status.textContent=`Importing ${i+1}/${targets.length} months · ${newCount} new game${newCount===1?'':'s'}`;try{const d=await getJSONRetry(targets[i]);const batch=d.games||[];loadedGames+=batch.length;for(const g of batch)if(!existing.has(key(g))){existing.add(key(g));newCount++}await putGames(batch);await sleep(80)}catch{failed++}}const games=await allGames();const mine=games.filter(g=>g.white?.username?.toLowerCase()===u.toLowerCase()||g.black?.username?.toLowerCase()===u.toLowerCase());renderFallback(games,u);window.dispatchEvent(new CustomEvent('chessGamesImported',{detail:{username:u,newCount,total:mine.length,archivesLoaded:targets.length-failed,archivesTotal:targets.length}}));if(failed===targets.length)throw new Error('Chess.com archives could not be downloaded. Please try again.');status.textContent=`${newCount?`${newCount} new game${newCount===1?'':'s'} imported`:'Up to date'} · ${mine.length} total games · ${targets.length-failed}/${targets.length} months loaded${failed?` · ${failed} failed`:''}`;if(failed)status.textContent+=' · tap Sync games again to retry failed months';collapseImportAfterSuccess()}
catch(e){status.textContent='Import failed: '+(e?.name==='AbortError'?'Chess.com request timed out':e.message)}finally{running=false;button.disabled=false;button.textContent='Import games'}}
function bind(){const b=$('sync');if(b&&!b.dataset.robustImport){b.dataset.robustImport='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();robustImport({compact:false})},true)}window.addEventListener('requestChessSync',()=>robustImport({compact:true}))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
