const $=id=>document.getElementById(id);
const DB_NAME='rk93-chess-analyser',STORE='games';
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function putGames(games){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite'),s=tx.objectStore(STORE);for(const g of games){g._key=g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`;s.put(g)}tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>{db.close();reject(tx.error)}})}
async function allGames(){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAll();r.onsuccess=()=>{db.close();resolve(r.result||[])};r.onerror=()=>{db.close();reject(r.error)}})}
async function getJSON(url,ms=10000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{headers:{Accept:'application/json'},signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}
function key(g){return g.url||`${g.end_time}-${g.white?.username}-${g.black?.username}`}
function pickArchives(archives,range){if(range==='all')return archives;if(range==='year')return archives.slice(-12);return archives.slice(-1)}
function renderFallback(games,u){const root=$('games');if(!root)return;const mine=games.filter(g=>g.white?.username?.toLowerCase()===u.toLowerCase()||g.black?.username?.toLowerCase()===u.toLowerCase()).sort((a,b)=>(b.end_time||0)-(a.end_time||0));root.innerHTML='';if(!mine.length){root.innerHTML='<div class="game">No saved games yet.</div>';return}for(const g of mine){const isWhite=g.white.username.toLowerCase()===u.toLowerCase(),me=isWhite?g.white:g.black,opp=isWhite?g.black:g.white,d=document.createElement('div');d.className='game';d.innerHTML=`<b>${me.username} ${me.rating??''}</b> — ${opp.username} ${opp.rating??''}<div class="muted">${new Date((g.end_time||0)*1000).toLocaleString()}</div>`;root.appendChild(d)}}
async function robustImport(){const button=$('sync'),status=$('status'),user=$('user'),range=$('importRange');if(!button||!user)return;const u=user.value.trim();if(!u){status.textContent='Enter a Chess.com username';return}button.disabled=true;button.textContent='Importing…';localStorage.setItem('chess-username',u);try{status.textContent='Finding Chess.com archives…';const a=await getJSON(`https://api.chess.com/pub/player/${encodeURIComponent(u)}/games/archives`);const targets=pickArchives(a.archives||[],range?.value||'month');if(!targets.length)throw new Error('No Chess.com game archives found for this user');const before=await allGames(),existing=new Set(before.map(key));let newCount=0,failed=0;for(let i=0;i<targets.length;i++){status.textContent=`Importing ${i+1}/${targets.length} · ${newCount} new game${newCount===1?'':'s'}`;try{const d=await getJSON(targets[i]);const batch=d.games||[];for(const g of batch)if(!existing.has(key(g))){existing.add(key(g));newCount++}await putGames(batch)}catch{failed++}}const games=await allGames();renderFallback(games,u);window.dispatchEvent(new CustomEvent('chessGamesImported',{detail:{username:u,newCount,total:games.length}}));if(failed===targets.length)throw new Error('Chess.com archives could not be downloaded. Please try again.');status.textContent=`${newCount?`${newCount} new game${newCount===1?'':'s'} imported`:'Up to date'} · ${targets.length-failed}/${targets.length} archive${targets.length===1?'':'s'} loaded${failed?` · ${failed} failed`:''}`}
catch(e){status.textContent='Import failed: '+(e?.name==='AbortError'?'Chess.com request timed out':e.message)}finally{button.disabled=false;button.textContent='Import games'}}
function bind(){const b=$('sync');if(!b)return;b.onclick=robustImport;b.addEventListener('click',e=>{e.stopImmediatePropagation();e.preventDefault();robustImport()},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
