import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';

const $=id=>document.getElementById(id);
const PREF='chess-analyser-pref:';
const pref=(k,f)=>localStorage.getItem(PREF+k)||f;
let chess=new Chess(),orientation='white',selected=null,lastMove=null;
let dragState=null;

function pieceSrc(color,type){
  const code={p:'P',r:'R',n:'N',b:'B',q:'Q',k:'K'}[type];
  const folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'};
  const folder=folders[pref('pieces','neo')]||folders.neo;
  return `https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${color}${code}.svg`;
}
function themeBoard(){const b=$('labBoard');if(!b)return;b.classList.remove('theme-green','theme-brown','theme-blue','theme-grey');b.classList.add('theme-'+pref('board','green'))}
function order(){const files=orientation==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=orientation==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function announcePosition(){window.dispatchEvent(new CustomEvent('chessPositionChanged',{detail:{fen:chess.fen(),context:'lab'}}))}
function render(){const b=$('labBoard');if(!b)return;b.innerHTML='';order().forEach(sq=>{const f=sq.charCodeAt(0)-97,r=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(f+r)%2?'dark':'light'}`;el.dataset.square=sq;if(selected===sq)el.classList.add('selected');if(lastMove&&(lastMove.from===sq||lastMove.to===sq))el.classList.add('last');const p=chess.get(sq);if(p){const img=document.createElement('img');img.className='piece labPiece';img.src=pieceSrc(p.color,p.type);img.draggable=false;img.alt='';img.addEventListener('pointerdown',e=>startDrag(e,sq,img));el.appendChild(img)}el.addEventListener('click',e=>{if(Date.now()-(dragState?.endedAt||0)<250)return;tap(sq)});b.appendChild(el)});themeBoard();announcePosition()}
function legalMove(from,to){const options=chess.moves({square:from,verbose:true}).filter(m=>m.to===to);if(!options.length)return false;lastMove=chess.move({from,to,promotion:options.some(m=>m.promotion)?'q':undefined});selected=null;clearAnalysis();render();return true}
function tap(sq){if(selected){if(legalMove(selected,sq))return;selected=null}const p=chess.get(sq);if(p&&p.color===chess.turn())selected=sq;render()}
function startDrag(e,from,img){const p=chess.get(from);if(!p||p.color!==chess.turn())return;e.preventDefault();selected=from;const ghost=img.cloneNode(true);ghost.classList.add('dragGhost');document.body.appendChild(ghost);const size=Math.max(44,img.getBoundingClientRect().width);ghost.style.width=size+'px';ghost.style.height=size+'px';dragState={from,ghost,pointerId:e.pointerId,moved:false,endedAt:0};positionGhost(e.clientX,e.clientY);img.setPointerCapture?.(e.pointerId);img.addEventListener('pointermove',onDragMove);img.addEventListener('pointerup',onDragEnd,{once:true});img.addEventListener('pointercancel',onDragCancel,{once:true});renderDragSelection(from)}
function renderDragSelection(from){document.querySelectorAll('#labBoard .sq').forEach(el=>el.classList.toggle('selected',el.dataset.square===from))}
function positionGhost(x,y){if(!dragState?.ghost)return;dragState.ghost.style.left=x+'px';dragState.ghost.style.top=y+'px'}
function onDragMove(e){if(!dragState)return;e.preventDefault();dragState.moved=true;positionGhost(e.clientX,e.clientY);document.querySelectorAll('#labBoard .sq.dragTarget').forEach(el=>el.classList.remove('dragTarget'));const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('#labBoard .sq');if(target&&target.dataset.square!==dragState.from)target.classList.add('dragTarget')}
function finishDrag(e,cancelled=false){if(!dragState)return;const state=dragState;state.ghost?.remove();document.querySelectorAll('#labBoard .sq.dragTarget').forEach(el=>el.classList.remove('dragTarget'));let moved=false;if(!cancelled&&state.moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('#labBoard .sq');if(target)moved=legalMove(state.from,target.dataset.square)}if(!moved){selected=state.from;render()}dragState={endedAt:Date.now()}}
function onDragEnd(e){finishDrag(e,false)}
function onDragCancel(e){finishDrag(e,true)}
function clearAnalysis(){$('labScore').textContent='—';$('labSource').textContent='Ready';$('labLine').textContent='Position changed. Tap Analyse position.';$('labEvalFill').style.height='50%';$('labArrows').innerHTML=''}
function score(pv){if(pv?.mate!==undefined&&pv?.mate!==null&&Number(pv.mate)!==0){const m=Number(pv.mate);return{n:m>0?20:-20,label:(m<0?'-':'')+'M'+Math.abs(m)}}const n=(Number(pv?.cp)||0)/100;return{n,label:(n>=0?'+':'')+n.toFixed(2)}}
function squareCenter(sq){const f=sq.charCodeAt(0)-97,r=Number(sq[1]),x=orientation==='white'?f:7-f,y=orientation==='white'?8-r:r-1;return{x:(x+.5)*100,y:(y+.5)*100}}
function draw(pvs){const svg=$('labArrows');svg.innerHTML='<defs><marker id="labArrow" markerWidth="5" markerHeight="5" refX="4.1" refY="2.5" orient="auto" markerUnits="strokeWidth"><path d="M0,0 L5,2.5 L0,5 Z" fill="#8bc34a"/></marker></defs>';pvs.slice(0,3).forEach((pv,i)=>{const u=String(pv.moves||'').trim().split(/\s+/)[0];if(!/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(u))return;const a=squareCenter(u.slice(0,2)),b=squareCenter(u.slice(2,4));svg.insertAdjacentHTML('beforeend',`<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" stroke="${['#8bc34a','#f4c542','#58a6ff'][i]}" stroke-width="${i?10:14}" stroke-linecap="round" opacity=".88" marker-end="url(#labArrow)"/>`)})}
async function cloud(fen){const r=await fetch(`https://lichess.org/api/cloud-eval?fen=${encodeURIComponent(fen)}&multiPv=3&variant=standard`,{headers:{Accept:'application/json'}});if(r.status===404)return null;if(!r.ok)throw new Error(`Cloud ${r.status}`);const j=await r.json();return j.pvs?.length?{source:'Lichess cloud',depth:j.depth,pvs:j.pvs.slice(0,3)}:null}
async function stockfish(fen){const r=await fetch('https://chess-api.com/v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fen,depth:14,variants:1,maxThinkingTime:180})});if(!r.ok)throw new Error(`Live engine ${r.status}`);const j=await r.json(),best=j.move||j.lan||'',cont=Array.isArray(j.continuationArr)?j.continuationArr.filter(Boolean):[],moves=[best,...cont.filter((m,i)=>!(i===0&&m===best))].filter(Boolean).join(' '),cp=j.eval!=null?Math.round(Number(j.eval)*100):Number(j.centipawns)||0;return{source:'Stockfish live',depth:j.depth||14,pvs:[{cp,mate:j.mate,moves}]}}
async function analyse(){const btn=$('labAnalyse');btn.disabled=true;btn.textContent='Analysing…';try{const fen=chess.fen(),mode=$('labEngine').value;let data;if(mode==='cloud'){data=await cloud(fen);if(!data)throw new Error('No cloud evaluation available')}else if(mode==='stockfish')data=await stockfish(fen);else{try{data=await cloud(fen)}catch{}if(!data)data=await stockfish(fen)}const s=score(data.pvs[0]);$('labScore').textContent=s.label;$('labSource').textContent=`${data.source} · depth ${data.depth??'—'}`;$('labLine').textContent='Best: '+(data.pvs[0].moves||'');$('labEvalFill').style.height=`${Math.max(3,Math.min(97,50+45*(2/Math.PI)*Math.atan(s.n/3)))}%`;draw(data.pvs)}catch(e){$('labLine').textContent='Could not analyse: '+e.message}finally{btn.disabled=false;btn.textContent='Analyse position'}}
function showTab(which){const lab=which==='lab';$('libraryView').hidden=lab;$('boardLabView').hidden=!lab;$('gamesTab').classList.toggle('active',!lab);$('boardLabTab').classList.toggle('active',lab);if(lab)render()}
function init(){if(!$('labBoard'))return;$('gamesTab').addEventListener('click',()=>showTab('games'));$('boardLabTab').addEventListener('click',()=>showTab('lab'));$('labAnalyse').addEventListener('click',analyse);$('labReset').addEventListener('click',()=>{chess=new Chess();selected=null;lastMove=null;clearAnalysis();render()});$('labFlip').addEventListener('click',()=>{orientation=orientation==='white'?'black':'white';render()});$('labEngine').value=pref('engine','auto');const settings=$('settingsToggleLab');if(settings)settings.addEventListener('click',()=>document.getElementById('settingsToggleLibrary')?.click());window.addEventListener('chessPreference',e=>{if(e.detail?.key==='pieces'||e.detail?.key==='board')render();if(e.detail?.key==='engine')$('labEngine').value=e.detail.value});render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
