const $=id=>document.getElementById(id);
const PREF='chess-analyser-pref:';
const pref=(k,f)=>localStorage.getItem(PREF+k)||f;
let active=false,selectedPiece='wQ',boardMap=new Map(),lastFen='start';
const pieceCode={P:'P',N:'N',B:'B',R:'R',Q:'Q',K:'K'};
function pieceSrc(color,type){const folders={neo:'chess_kaneo',bases:'chess_kaneo_midnight',classic:'chess_maestro_bw'},folder=folders[pref('pieces','neo')]||folders.neo;return `https://cdn.jsdelivr.net/gh/Kadagaden/chess-pieces@master/${folder}/${color}${type}.svg`}
function parseFen(fen){boardMap.clear();if(!fen||fen==='start')fen='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1';const rows=fen.split(' ')[0].split('/');for(let ri=0;ri<8;ri++){let f=0;for(const ch of rows[ri]){if(/\d/.test(ch)){f+=Number(ch);continue}const color=ch===ch.toUpperCase()?'w':'b',type=ch.toUpperCase();boardMap.set(String.fromCharCode(97+f)+(8-ri),color+type);f++}}}
function toFen(){const rows=[];for(let r=8;r>=1;r--){let row='',empty=0;for(let f=0;f<8;f++){const p=boardMap.get(String.fromCharCode(97+f)+r);if(!p){empty++;continue}if(empty){row+=empty;empty=0}const [c,t]=p;row+=c==='w'?t:t.toLowerCase()}if(empty)row+=empty;rows.push(row)}return `${rows.join('/')} ${$('setupTurn').value} - - 0 1`}
function renderPalette(){const root=$('setupPalette');root.innerHTML='';for(const color of ['w','b'])for(const type of ['K','Q','R','B','N','P']){const b=document.createElement('button');b.type='button';b.className='setupPiece'+(selectedPiece===color+type?' selected':'');b.dataset.piece=color+type;b.innerHTML=`<img src="${pieceSrc(color,type)}" alt="${color==='w'?'White':'Black'} ${type}">`;b.addEventListener('click',()=>{selectedPiece=color+type;renderPalette()});root.appendChild(b)}const er=document.createElement('button');er.type='button';er.className='setupPiece eraser'+(selectedPiece==='erase'?' selected':'');er.textContent='⌫';er.title='Eraser';er.addEventListener('click',()=>{selectedPiece='erase';renderPalette()});root.appendChild(er)}
function currentOrientation(){const first=$('labBoard')?.querySelector('.sq')?.dataset.square;return first==='h1'?'black':'white'}
function order(){const o=currentOrientation(),files=o==='white'?['a','b','c','d','e','f','g','h']:['h','g','f','e','d','c','b','a'],ranks=o==='white'?[8,7,6,5,4,3,2,1]:[1,2,3,4,5,6,7,8];return ranks.flatMap(r=>files.map(f=>f+r))}
function renderSetupBoard(){if(!active)return;const b=$('labBoard');b.innerHTML='';order().forEach(sq=>{const f=sq.charCodeAt(0)-97,r=Number(sq[1]),el=document.createElement('div');el.className=`sq ${(f+r)%2?'dark':'light'}`;el.dataset.square=sq;const p=boardMap.get(sq);if(p){const img=document.createElement('img');img.className='piece';img.src=pieceSrc(p[0],p[1]);img.alt='';img.draggable=false;el.appendChild(img)}el.addEventListener('click',()=>{if(selectedPiece==='erase')boardMap.delete(sq);else boardMap.set(sq,selectedPiece);renderSetupBoard()});b.appendChild(el)});for(const t of ['green','brown','blue','grey'])b.classList.remove('theme-'+t);b.classList.add('theme-'+pref('board','green'));$('labArrows').innerHTML=''}
function validate(){let wk=0,bk=0;for(const p of boardMap.values()){if(p==='wK')wk++;if(p==='bK')bk++}if(wk!==1||bk!==1)return 'Position must contain exactly one white king and one black king.';return ''}
function enter(){active=true;$('setupPanel').hidden=false;$('setupToggle').textContent='Exit setup';$('labAnalyse').disabled=true;parseFen(lastFen);renderPalette();renderSetupBoard();$('setupStatus').textContent='Choose a piece, then tap any square to place it. Use Eraser to remove pieces.'}
function exit(){active=false;$('setupPanel').hidden=true;$('setupToggle').textContent='Position setup';$('labAnalyse').disabled=false;window.dispatchEvent(new CustomEvent('refreshLabBoard'))}
function init(){if(!$('setupToggle'))return;window.addEventListener('chessPositionChanged',e=>{if(e.detail?.context==='lab'&&!active)lastFen=e.detail.fen});$('setupToggle').addEventListener('click',()=>active?exit():enter());$('setupClear').addEventListener('click',()=>{boardMap.clear();renderSetupBoard()});$('setupStart').addEventListener('click',()=>{parseFen('start');$('setupTurn').value='w';renderSetupBoard()});$('setupCancel').addEventListener('click',exit);$('setupApply').addEventListener('click',()=>{const error=validate();if(error){$('setupStatus').textContent=error;return}const fen=toFen();lastFen=fen;active=false;$('setupPanel').hidden=true;$('setupToggle').textContent='Position setup';$('labAnalyse').disabled=false;window.dispatchEvent(new CustomEvent('loadLabFen',{detail:{fen}}))});window.addEventListener('chessPreference',e=>{if(active&&(e.detail?.key==='pieces'||e.detail?.key==='board')){renderPalette();renderSetupBoard()}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
