import { Chess } from 'https://cdn.jsdelivr.net/npm/chess.js@1.4.0/+esm';
import { cacheSet,simpleHash,getPositionEval,setPositionEval } from './analysis-store.js';

const $=id=>document.getElementById(id);
const LABELS=['Brilliant','Great','Best','Excellent','Good','Book','Inaccuracy','Mistake','Blunder'];
let active=null,token=0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

function ensureCss(){if(document.getElementById('reviewProCss'))return;const l=document.createElement('link');l.id='reviewProCss';l.rel='stylesheet';l.href='review-pro.css';document.head.appendChild(l)}
function moves(){return [...document.querySelectorAll('#moves .move')]}
function sans(){return moves().map(e=>e.childNodes[0]?.textContent?.trim()||e.textContent.trim())}
function key(){return simpleHash(`${$('gameTitle')?.textContent||''}|${sans().join(' ')}`)}
function build(){const c=new Chess(),positions=[c.fen()],ucis=[];for(const san of sans()){try{const m=c.move(san);ucis.push(m.from+m.to+(m.promotion||''));positions.push(c.fen())}catch{return null}}return{positions,ucis}}
function firstMove(s){const u=String(s||'').trim().split(/\s+/)[0];return /^[a-h][1-8][a-h][1-8][qrbn]?$/.test(u)?u:''}
function whitePerspective(raw,fen){const turn=String(fen).split(' ')[1];return turn==='b'?-Number(raw||0):Number(raw||0)}
function terminal(fen){try{const c=new Chess(fen);if(c.isCheckmate())return c.turn()==='w'?-10000:10000;if(c.isDraw()||c.isStalemate()||c.isInsufficientMaterial())return 0}catch{}return null}
async function fetchExact(fen){const t=terminal(fen);if(t!==null)return{cp:t,best:'',exact:true,source:'terminal'};const cached=await getPositionEval('cloud',fen).catch(()=>null);if(cached?.pvs?.length){const p=cached.pvs[0],raw=p.mate?((Number(p.mate)>0)?10000:-10000):Number(p.cp)||0;return{cp:whitePerspective(raw,fen),best:firstMove(p.moves),exact:true,source:'cloud-cache'}}
  try{const r=await fetch(`https://lichess.org/api/cloud-eval?fen=${encodeURIComponent(fen)}&multiPv=1&variant=standard`,{headers:{Accept:'application/json'}});if(r.status===429){await sleep(900);return null}if(r.ok){const j=await r.json();if(j?.pvs?.length){await setPositionEval('cloud',fen,{source:'Lichess cloud',depth:j.depth||0,pvs:j.pvs.slice(0,1)}).catch(()=>{});const p=j.pvs[0],raw=p.mate?((Number(p.mate)>0)?10000:-10000):Number(p.cp)||0;return{cp:whitePerspective(raw,fen),best:firstMove(p.moves),exact:true,source:'cloud'}}}}catch{}
  try{const r=await fetch('https://chess-api.com/v1',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({fen,depth:13,variants:1,maxThinkingTime:220})});if(r.ok){const j=await r.json(),raw=j.mate?((Number(j.mate)>0)?10000:-10000):(j.eval!=null?Math.round(Number(j.eval)*100):Number(j.centipawns)||0),best=j.move||j.lan||'';return{cp:whitePerspective(raw,fen),best:/^[a-h][1-8][a-h][1-8][qrbn]?$/.test(best)?best:'',exact:true,source:'live'}}}catch{}
  return null;
}
function cpl(before,after,ply){return Math.max(0,ply%2===1?before-after:after-before)}
function classify(i,ctx,evals,bests,exact){const ply=i+1,loss=cpl(evals[i],evals[i+1],ply),played=ctx.ucis[i],best=bests[i]||'',matched=best&&played===best,verified=exact[i]&&exact[i+1];if(verified&&matched){if(loss<=4&&i>8){const gain=ply%2===1?evals[i+1]-evals[i]:evals[i]-evals[i+1];if(gain>=140)return'Brilliant';if(gain>=65)return'Great'}return'Best'}if(!verified){if(loss>=220)return'Blunder';if(loss>=130)return'Mistake';if(loss>=70)return'Inaccuracy';return'Good'}if(i<10&&loss<=20)return'Book';if(loss<=18)return'Excellent';if(loss<=55)return'Good';if(loss<=115)return'Inaccuracy';if(loss<=220)return'Mistake';return'Blunder'}
function accuracy(losses){if(!losses.length)return 100;const xs=losses.map(x=>Math.min(700,Math.max(0,x))),mean=xs.reduce((a,b)=>a+b,0)/xs.length,rms=Math.sqrt(xs.reduce((a,b)=>a+b*b,0)/xs.length),effective=.55*mean+.45*rms;return Math.round(Math.max(0,Math.min(100,100*Math.exp(-effective/155)))*10)/10}
function refreshSummary(data){const counts={white:Object.fromEntries(LABELS.map(x=>[x,0])),black:Object.fromEntries(LABELS.map(x=>[x,0]))};data.labels.forEach((x,i)=>counts[i%2===0?'white':'black'][x]++);const b=$('reviewBreakdown');if(b)b.innerHTML=LABELS.map(label=>`<div class="reviewBreakRow"><span class="label">${label}</span><span class="left">${counts.white[label]||0}</span><span class="reviewBreakIcon badge-${label.toLowerCase()}">${({Brilliant:'!!',Great:'!',Best:'★',Excellent:'✓',Good:'✓',Book:'📖',Inaccuracy:'?!',Mistake:'?',Blunder:'??'})[label]}</span><span class="right">${counts.black[label]||0}</span></div>`).join('');const p=$('reviewSummaryPlayers');if(p){const names=($('gameTitle')?.textContent||'White — Black').split(' — ');p.innerHTML=`<div class="reviewSummaryPlayer"><div class="name">${names[0]||'White'}</div><div class="accuracy">${data.whiteAccuracy.toFixed(1)}</div></div><div class="reviewSummaryPlayer"><div class="name">${names[1]||'Black'}</div><div class="accuracy">${data.blackAccuracy.toFixed(1)}</div></div>`}}
function refreshTags(data){moves().forEach((el,i)=>{let t=el.querySelector('.moveTag');if(!t){t=document.createElement('span');el.appendChild(t)}const label=data.labels[i]||'Good';t.className='moveTag tag-'+label.toLowerCase();t.textContent=label;t.title=data.moveVerified[i]?'Engine-verified':'Estimated'})}
function ensureProgress(){const s=$('reviewSummaryScreen');if(!s)return null;let box=$('reviewProLoading');if(box)return box;box=document.createElement('div');box.id='reviewProLoading';box.className='reviewProLoading';box.innerHTML='<span>Refining review…</span><span id="reviewProPct">0%</span>';const bar=document.createElement('div');bar.className='reviewProProgress';bar.innerHTML='<span></span>';box.after(bar);s.querySelector('.reviewSummaryTop')?.after(box);return box}
function setProgress(done,total){ensureProgress();const pct=Math.round(done/Math.max(1,total)*100);if($('reviewProPct'))$('reviewProPct').textContent=pct+'%';document.querySelector('.reviewProProgress>span')?.style.setProperty('width',pct+'%');if(done>=total){setTimeout(()=>{const x=$('reviewProLoading');if(x)x.remove();document.querySelector('.reviewProProgress')?.remove()},350)}}
function decorateReview(){const v=$('analysisView');if(v)v.classList.add('reviewProMode');const c=$('reviewGuideCard');if(c&&!c.querySelector('.reviewProCoach')){const title=c.querySelector('.reviewGuideTitle'),comment=c.querySelector('.reviewGuideComment');const wrap=document.createElement('div');wrap.className='reviewProCoach';wrap.innerHTML='<div class="reviewProCoachFace">♞</div><div class="reviewProCoachText"></div>';const text=wrap.querySelector('.reviewProCoachText');if(title)text.appendChild(title);if(comment)text.appendChild(comment);c.insertBefore(wrap,c.firstChild)}ensureMoveStrip()}
function ensureMoveStrip(){if($('reviewProMoveStrip'))return;const side=document.querySelector('#analysisView .sidePanel');if(!side)return;const strip=document.createElement('div');strip.id='reviewProMoveStrip';strip.className='reviewProMoveStrip';side.insertBefore(strip,side.firstChild);renderMoveStrip()}
function renderMoveStrip(){const strip=$('reviewProMoveStrip');if(!strip)return;strip.innerHTML='';moves().forEach((m,i)=>{const b=document.createElement('button');b.type='button';b.className='reviewProMoveChip';const san=(m.childNodes[0]?.textContent||m.textContent).trim();b.textContent=`${Math.floor(i/2)+1}${i%2?'…':'.'} ${san}`;const lab=active?.labels?.[i];if(['Mistake','Blunder','Inaccuracy'].includes(lab))b.classList.add('bad');else if(['Best','Great','Brilliant'].includes(lab))b.classList.add('good');if(m.classList.contains('active'))b.classList.add('active');b.onclick=()=>m.click();strip.appendChild(b)});const a=strip.querySelector('.active');a?.scrollIntoView({inline:'center',block:'nearest'})}
async function refine(detail){const data=detail?.data;if(!data)return;active=data;decorateReview();const ctx=build();if(!ctx)return;const my=++token,n=ctx.positions.length,evals=new Array(n),bests=new Array(n).fill(''),exact=new Array(n).fill(false);for(let i=0;i<n;i++){if(my!==token)return;const r=await fetchExact(ctx.positions[i]);if(r){evals[i]=r.cp;bests[i]=r.best;exact[i]=true}else if(data.positionExact?.[i]){const raw=Number(data.evals?.[i]);evals[i]=whitePerspective(raw,ctx.positions[i]);exact[i]=true;bests[i]=data.bestMoves?.[i]||''}else evals[i]=null;setProgress(i+1,n);await sleep(35)}
  for(let i=0;i<n;i++)if(evals[i]==null){let a=i-1,b=i+1;while(a>=0&&evals[a]==null)a--;while(b<n&&evals[b]==null)b++;evals[i]=a>=0&&b<n?Math.round(evals[a]+(evals[b]-evals[a])*(i-a)/(b-a)):a>=0?evals[a]:b<n?evals[b]:0}
  const labels=[],losses=[],wc=[],bc=[];for(let i=0;i<ctx.ucis.length;i++){const loss=cpl(evals[i],evals[i+1],i+1);losses.push(loss);labels.push(classify(i,ctx,evals,bests,exact));(i%2===0?wc:bc).push(loss)}Object.assign(data,{evals,bestMoves:bests,positionExact:exact,moveVerified:labels.map((_,i)=>exact[i]&&exact[i+1]),labels,cpLosses:losses,whiteAccuracy:accuracy(wc),blackAccuracy:accuracy(bc),correctionVersion:3,accuracyMethod:'normalized-exact-cpl-v3'});active=data;refreshTags(data);refreshSummary(data);renderMoveStrip();await cacheSet('review',key(),data).catch(()=>{});window.dispatchEvent(new CustomEvent('reviewNavigation'));}
function init(){ensureCss();window.addEventListener('gameReviewReady',e=>refine(e.detail).catch(()=>{}));window.addEventListener('reviewNavigation',()=>{decorateReview();renderMoveStrip()});document.addEventListener('click',e=>{if(e.target.closest?.('#runReview,#reviewStartBtn,#reviewSummaryScreen'))setTimeout(decorateReview,0)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
