const $=id=>document.getElementById(id);
const API='https://api.chess.com/pub';
const state={category:'live_blitz',players:[],selected:null,archives:[],archiveIndex:-1,games:[],loading:false};
const categoryToTime={live_blitz:'blitz',live_rapid:'rapid',live_bullet:'bullet'};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function getJSON(url){const r=await fetch(url,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}
function cardName(p){return p.name||p.username||'Unknown'}
function renderPlayers(){const root=$('topPlayersGrid');if(!root)return;if(!state.players.length){root.innerHTML='<div class="card topPlayersEmpty">No leaderboard data available.</div>';return}root.innerHTML=state.players.map((p,i)=>`<button class="topPlayerCard${state.selected?.username===p.username?' active':''}" type="button" data-user="${esc(p.username)}"><div class="topPlayerRank">#${i+1}</div><div class="topPlayerName">${esc(cardName(p))}</div><div class="topPlayerRating">${Number(p.score||p.rating||0)||'—'}</div><div class="topPlayerMeta">${esc(p.username)}</div></button>`).join('');root.querySelectorAll('.topPlayerCard').forEach(b=>b.addEventListener('click',()=>selectPlayer(b.dataset.user)))}
function resultText(g,user){const white=(g.white?.username||'').toLowerCase()===user.toLowerCase(),me=white?g.white:g.black;if(me?.result==='win')return'Win';if(['checkmated','resigned','timeout','lose','abandoned'].includes(me?.result))return'Loss';return'Draw'}
function fmtDate(sec){try{return new Date(Number(sec||0)*1000).toLocaleString()}catch{return''}}
function renderGames(){const root=$('topPlayerGames');if(!root)return;if(!state.selected){root.innerHTML='<div class="card topPlayersEmpty">Choose a player to see recent games.</div>';return}const tc=categoryToTime[state.category],games=state.games.filter(g=>!tc||g.time_class===tc).sort((a,b)=>(b.end_time||0)-(a.end_time||0)).slice(0,60);const month=state.archives[state.archiveIndex]?.split('/').slice(-2).join('-')||'';root.innerHTML=`<div class="card"><div class="topPlayersHead"><div><h2>${esc(cardName(state.selected))}</h2><div class="muted">${esc(state.selected.username)} · ${esc(tc||'games')} · ${esc(month)}</div></div><div class="muted">${games.length} shown</div></div><div>${games.length?games.map(g=>{const w=g.white?.username||'White',b=g.black?.username||'Black',wr=g.white?.rating??'',br=g.black?.rating??'',res=resultText(g,state.selected.username),url=g.url||'';return `<div class="eliteGame"><div class="eliteGameMain"><div class="eliteGamePlayers">${esc(w)} ${esc(wr)} — ${esc(b)} ${esc(br)}</div><div class="eliteGameMeta">${esc(res)} · ${esc(g.time_class||'game')} · ${esc(fmtDate(g.end_time))}</div></div><div class="eliteGameActions">${url?`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener noreferrer">View game</a>`:''}</div></div>`}).join(''):'<div class="topPlayersEmpty">No games for this time control in this month.</div>'}</div></div>${state.archiveIndex>0?'<div class="topPlayersPager"><button id="topPlayersOlder" class="btn" type="button">Load previous month</button></div>':''}`;const older=$('topPlayersOlder');if(older)older.addEventListener('click',loadOlder)}
async function enrichPlayer(p){try{const d=await getJSON(`${API}/player/${encodeURIComponent(p.username)}`);return{...p,name:d.name||p.username,title:d.title||'',country:d.country||''}}catch{return{...p,name:p.username}}}
async function loadLeaderboard(){if(state.loading)return;state.loading=true;const status=$('topPlayersStatus');if(status)status.textContent='Loading current Chess.com leaders…';try{const d=await getJSON(`${API}/leaderboards`),raw=(d[state.category]||[]).slice(0,20);state.players=await Promise.all(raw.map(enrichPlayer));renderPlayers();if(status)status.textContent=`Current top ${state.players.length} · ${categoryToTime[state.category]}`;if(state.players[0])await selectPlayer(state.players[0].username,true)}catch(e){if(status)status.textContent='Could not load Chess.com leaderboard: '+e.message;state.players=[];renderPlayers()}finally{state.loading=false}}
async function selectPlayer(username,quiet=false){const p=state.players.find(x=>x.username===username);if(!p)return;state.selected=p;state.games=[];renderPlayers();renderGames();const status=$('topPlayersStatus');if(status&&!quiet)status.textContent=`Loading ${cardName(p)}…`;try{const a=await getJSON(`${API}/player/${encodeURIComponent(username)}/games/archives`);state.archives=a.archives||[];state.archiveIndex=state.archives.length-1;if(state.archiveIndex<0){state.games=[];renderGames();return}await loadArchive()}catch(e){if(status)status.textContent='Could not load games: '+e.message;state.games=[];renderGames()}}
async function loadArchive(){const status=$('topPlayersStatus'),url=state.archives[state.archiveIndex];if(!url)return;if(status)status.textContent=`Loading ${cardName(state.selected)} games…`;try{const d=await getJSON(url);state.games=d.games||[];renderGames();if(status)status.textContent=`${cardName(state.selected)} · ${categoryToTime[state.category]} games`}catch(e){if(status)status.textContent='Could not load games: '+e.message}}
async function loadOlder(){if(state.archiveIndex<=0)return;state.archiveIndex--;await loadArchive()}
function init(){if(!$('topPlayersView'))return;$('topPlayersCategory')?.addEventListener('change',e=>{state.category=e.target.value;state.selected=null;state.games=[];loadLeaderboard()});window.addEventListener('topPlayersTabOpened',()=>{if(!state.players.length)loadLeaderboard()});renderGames()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
