const $=id=>document.getElementById(id);
const PAGE_SIZE=20;
let page=1,filterResult='all',filterSpeed='all',query='';

function ensureStyles(){if(document.getElementById('uxShellStyles'))return;const l=document.createElement('link');l.id='uxShellStyles';l.rel='stylesheet';l.href='ux-shell.css';document.head.appendChild(l)}
function classifySpeed(text=''){const m=text.match(/(?:·\s*)?(\d+)(?:\+(\d+))?\s*(?:min)?/i);if(!m)return'other';const mins=Number(m[1])||0;if(mins<=2)return'bullet';if(mins<=5)return'blitz';return'rapid'}
function cardResult(el){const t=el.textContent||'';if(/\bWin\b/i.test(t))return'win';if(/\bLoss\b/i.test(t))return'loss';if(/\bDraw\b/i.test(t))return'draw';return'other'}
function cardSpeed(el){return classifySpeed(el.querySelector('.muted')?.textContent||'')}
function filteredCards(){return [...document.querySelectorAll('#games > .game')].filter(el=>{const text=(el.textContent||'').toLowerCase();return (filterResult==='all'||cardResult(el)===filterResult)&&(filterSpeed==='all'||cardSpeed(el)===filterSpeed)&&(!query||text.includes(query.toLowerCase()))})}
function renderPagination(){const root=$('gamesPager');if(!root)return;const all=[...document.querySelectorAll('#games > .game')],matches=filteredCards(),pages=Math.max(1,Math.ceil(matches.length/PAGE_SIZE));page=Math.max(1,Math.min(page,pages));all.forEach(x=>x.hidden=true);matches.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE).forEach(x=>x.hidden=false);root.innerHTML=`<button class="btn" id="gamesPrev" ${page<=1?'disabled':''}>← Previous</button><span>${matches.length?`${(page-1)*PAGE_SIZE+1}–${Math.min(page*PAGE_SIZE,matches.length)} of ${matches.length}`:'0 games'}</span><button class="btn" id="gamesNext" ${page>=pages?'disabled':''}>Next →</button>`;$('gamesPrev')?.addEventListener('click',()=>{page--;renderPagination();document.querySelector('#gamesUxToolbar')?.scrollIntoView({behavior:'smooth',block:'start'})});$('gamesNext')?.addEventListener('click',()=>{page++;renderPagination();document.querySelector('#gamesUxToolbar')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function revealImport(){const top=document.querySelector('#libraryView > .topbar'),sync=document.querySelector('#libraryView > .syncCard');top?.classList.add('uxRevealed');sync?.classList.add('uxRevealed');sync?.scrollIntoView({behavior:'smooth',block:'start'})}
function openSettings(){const p=$('settingsPanel');if(!p)return;if(p.parentElement!==document.body)document.body.appendChild(p);p.hidden=false;p.classList.add('open');document.querySelectorAll('[data-piece-style]').forEach(b=>b.classList.toggle('selected',b.dataset.pieceStyle===(localStorage.getItem('chess-analyser-pref:pieces')||'classic')));document.querySelectorAll('[data-board-theme]').forEach(b=>b.classList.toggle('selected',b.dataset.boardTheme===(localStorage.getItem('chess-analyser-pref:board')||'green')))}
function ensureGameToolbar(){const games=$('games');if(!games||$('gamesUxToolbar'))return;const wrap=document.createElement('div');wrap.id='gamesUxToolbar';wrap.className='gamesUxToolbar';wrap.innerHTML=`<div class="gamesUxTop"><strong>Your games</strong><div class="gamesUxButtons"><button id="gamesSettings" class="btn" type="button">⚙ Settings</button><button id="manageImport" class="btn" type="button">↻ Import / sync</button></div></div><div class="gamesFilters"><input id="gameSearch" class="input" placeholder="Search opponent" aria-label="Search games"><select id="gameResultFilter" class="input"><option value="all">All results</option><option value="win">Wins</option><option value="loss">Losses</option><option value="draw">Draws</option></select><select id="gameSpeedFilter" class="input"><option value="all">All time controls</option><option value="rapid">Rapid</option><option value="blitz">Blitz</option><option value="bullet">Bullet</option></select></div>`;games.parentNode.insertBefore(wrap,games);const pager=document.createElement('div');pager.id='gamesPager';pager.className='gamesPager';games.parentNode.insertBefore(pager,games.nextSibling);$('gameSearch')?.addEventListener('input',e=>{query=e.target.value;page=1;renderPagination()});$('gameResultFilter')?.addEventListener('change',e=>{filterResult=e.target.value;page=1;renderPagination()});$('gameSpeedFilter')?.addEventListener('change',e=>{filterSpeed=e.target.value;page=1;renderPagination()});$('manageImport')?.addEventListener('click',revealImport);$('gamesSettings')?.addEventListener('click',openSettings)}
function updateLibraryChrome(){const cards=[...document.querySelectorAll('#games > .game')],hasGames=cards.length>0&&!cards.some(x=>/No saved games yet/i.test(x.textContent||''));const top=document.querySelector('#libraryView > .topbar'),sync=document.querySelector('#libraryView > .syncCard');if(hasGames){top?.classList.add('uxCollapsed');sync?.classList.add('uxCollapsed');ensureGameToolbar();renderPagination()}else{top?.classList.remove('uxCollapsed');sync?.classList.remove('uxCollapsed')}}
function decorateNav(){const nav=document.querySelector('.homeTabs');if(!nav)return;nav.classList.add('modernNav');for(const b of nav.querySelectorAll('.homeTab'))b.setAttribute('data-label',b.textContent.trim())}
function observe(){ensureStyles();decorateNav();updateLibraryChrome();const nav=document.querySelector('.homeTabs');if(nav)new MutationObserver(decorateNav).observe(nav,{childList:true});const games=$('games');if(games)new MutationObserver(()=>{clearTimeout(observe.t);observe.t=setTimeout(updateLibraryChrome,30)}).observe(games,{childList:true,subtree:true});document.addEventListener('click',e=>{if(e.target.closest('.homeTab'))setTimeout(decorateNav,0)},true);setTimeout(updateLibraryChrome,250);setTimeout(updateLibraryChrome,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
