const $=id=>document.getElementById(id);
const PAGE_SIZE=20,DB_NAME='rk93-chess-analyser',STORE='games';
let page=1,filterResult='all',filterSpeed='all',query='',lastViewId='gamesTab';
const NAV_ICONS={
  gamesTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 3h8a2 2 0 0 1 2 2v14l-6-3-6 3V5a2 2 0 0 1 2-2Z"/></svg>',
  boardLabTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h16v16H4V4Zm0 8h16M12 4v16"/></svg>',
  explorerTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg>',
  puzzlesTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 3h6v4a2 2 0 1 0 4 0v6h-4a2 2 0 1 0 0 4v4H9v-4a2 2 0 1 0-4 0v-6h4a2 2 0 1 0 0-4V3Z"/></svg>',
  analyticsTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 20V10m7 10V4m7 16v-7"/></svg>',
  topPlayersTab:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 18h14M7 18l1-8 4 3 4-3 1 8M8 7l-2-3m10 3 2-3M12 8V3"/></svg>',
  settingsNav:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.87l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.87.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.87l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.87-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.4.28.75.63 1 1 .23.34.37.73.4 1.1v.1h.1v1.6h-.1v.1c-.03.37-.17.76-.4 1.1-.25.37-.6.72-1 1Z"/></svg>'
};
function ensureStyles(){if(document.getElementById('uxShellStyles'))return;const l=document.createElement('link');l.id='uxShellStyles';l.rel='stylesheet';l.href='ux-shell.css';document.head.appendChild(l)}
function classifySpeed(text=''){const m=text.match(/(?:·\s*)?(\d+)(?:\+(\d+))?\s*(?:min)?/i);if(!m)return'other';const mins=Number(m[1])||0;if(mins<=2)return'bullet';if(mins<=5)return'blitz';return'rapid'}
function cardResult(el){const t=el.textContent||'';if(/\bWin\b/i.test(t))return'win';if(/\bLoss\b/i.test(t))return'loss';if(/\bDraw\b/i.test(t))return'draw';return'other'}
function cardSpeed(el){return classifySpeed(el.querySelector('.muted')?.textContent||'')}
function filteredCards(){return [...document.querySelectorAll('#games > .game')].filter(el=>{const text=(el.textContent||'').toLowerCase();return (filterResult==='all'||cardResult(el)===filterResult)&&(filterSpeed==='all'||cardSpeed(el)===filterSpeed)&&(!query||text.includes(query.toLowerCase()))})}
function renderPagination(){const root=$('gamesPager');if(!root)return;const all=[...document.querySelectorAll('#games > .game')],matches=filteredCards(),pages=Math.max(1,Math.ceil(matches.length/PAGE_SIZE));page=Math.max(1,Math.min(page,pages));all.forEach(x=>x.hidden=true);matches.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE).forEach(x=>x.hidden=false);root.innerHTML=`<button class="btn" id="gamesPrev" ${page<=1?'disabled':''}>← Previous</button><span>${matches.length?`${(page-1)*PAGE_SIZE+1}–${Math.min(page*PAGE_SIZE,matches.length)} of ${matches.length}`:'0 games'}</span><button class="btn" id="gamesNext" ${page>=pages?'disabled':''}>Next →</button>`;$('gamesPrev')?.addEventListener('click',()=>{page--;renderPagination();$('gamesUxToolbar')?.scrollIntoView({behavior:'smooth',block:'start'})});$('gamesNext')?.addEventListener('click',()=>{page++;renderPagination();$('gamesUxToolbar')?.scrollIntoView({behavior:'smooth',block:'start'})})}
function revealImport(){const top=document.querySelector('#libraryView > .topbar'),sync=document.querySelector('#libraryView > .syncCard');top?.classList.add('uxRevealed');sync?.classList.add('uxRevealed');sync?.scrollIntoView({behavior:'smooth',block:'start'})}
function ensureGameToolbar(){const games=$('games');if(!games||$('gamesUxToolbar'))return;const wrap=document.createElement('div');wrap.id='gamesUxToolbar';wrap.className='gamesUxToolbar';wrap.innerHTML=`<div class="gamesUxTop"><strong>Your games</strong><button id="manageImport" class="btn compactSync" type="button">↻ Sync games</button></div><div class="gamesFilters"><input id="gameSearch" class="input" placeholder="Search opponent" aria-label="Search games"><select id="gameResultFilter" class="input"><option value="all">All results</option><option value="win">Wins</option><option value="loss">Losses</option><option value="draw">Draws</option></select><select id="gameSpeedFilter" class="input"><option value="all">All time controls</option><option value="rapid">Rapid</option><option value="blitz">Blitz</option><option value="bullet">Bullet</option></select></div>`;games.parentNode.insertBefore(wrap,games);const pager=document.createElement('div');pager.id='gamesPager';pager.className='gamesPager';games.parentNode.insertBefore(pager,games.nextSibling);$('gameSearch')?.addEventListener('input',e=>{query=e.target.value;page=1;renderPagination()});$('gameResultFilter')?.addEventListener('change',e=>{filterResult=e.target.value;page=1;renderPagination()});$('gameSpeedFilter')?.addEventListener('change',e=>{filterSpeed=e.target.value;page=1;renderPagination()});$('manageImport')?.addEventListener('click',revealImport)}
function dbHasGames(){return new Promise(resolve=>{try{const r=indexedDB.open(DB_NAME,1);r.onsuccess=()=>{const db=r.result;try{const q=db.transaction(STORE,'readonly').objectStore(STORE).count();q.onsuccess=()=>{db.close();resolve(q.result>0)};q.onerror=()=>{db.close();resolve(false)}}catch{db.close();resolve(false)}};r.onerror=()=>resolve(false)}catch{resolve(false)}})}
function collapseLibrary(hasGames){const lib=$('libraryView'),top=document.querySelector('#libraryView > .topbar'),sync=document.querySelector('#libraryView > .syncCard');lib?.classList.toggle('hasSavedGames',!!hasGames);if(hasGames){top?.classList.add('uxCollapsed');sync?.classList.add('uxCollapsed');if(!sync?.classList.contains('uxRevealed'))sync?.classList.remove('uxRevealed');ensureGameToolbar();renderPagination()}else{top?.classList.remove('uxCollapsed');sync?.classList.remove('uxCollapsed')}}
async function updateLibraryChrome(){const cards=[...document.querySelectorAll('#games > .game')],domHas=cards.length>0&&!cards.some(x=>/No saved games yet/i.test(x.textContent||''));if(domHas){collapseLibrary(true);return}collapseLibrary(await dbHasGames())}
function ensureSettingsNav(){const nav=document.querySelector('.homeTabs');if(!nav||$('settingsNav'))return;const b=document.createElement('button');b.id='settingsNav';b.className='homeTab settingsNav';b.type='button';b.textContent='Settings';b.setAttribute('aria-label','Settings');nav.appendChild(b)}
function paintNavButton(b){const label=b.dataset.label||b.textContent.trim()||'Menu';b.dataset.label=label;const icon=NAV_ICONS[b.id];if(!icon)return;if(!b.querySelector('.navIcon'))b.innerHTML=`<span class="navIcon">${icon}</span><span class="navLabel">${label}</span>`}
function setOnlyActive(id){document.querySelectorAll('.homeTabs .homeTab').forEach(b=>b.classList.toggle('active',b.id===id));if(id!=='settingsNav')lastViewId=id}
function decorateNav(){const nav=document.querySelector('.homeTabs');if(!nav)return;ensureSettingsNav();nav.classList.add('modernNav');nav.querySelectorAll('.homeTab').forEach(paintNavButton)}
function openSettingsFromNav(){window.dispatchEvent(new CustomEvent('openChessSettings'));setOnlyActive('settingsNav')}
function observe(){ensureStyles();decorateNav();updateLibraryChrome();const nav=document.querySelector('.homeTabs');if(nav)new MutationObserver(()=>decorateNav()).observe(nav,{childList:true});const games=$('games');if(games)new MutationObserver(()=>{clearTimeout(observe.t);observe.t=setTimeout(updateLibraryChrome,30)}).observe(games,{childList:true,subtree:true});document.addEventListener('click',e=>{const tab=e.target.closest?.('.homeTabs .homeTab');if(!tab)return;if(tab.id==='settingsNav'){e.preventDefault();e.stopPropagation();openSettingsFromNav();return}setOnlyActive(tab.id);setTimeout(()=>setOnlyActive(tab.id),0)},true);window.addEventListener('chessSettingsClosed',()=>setOnlyActive(lastViewId||'gamesTab'));setTimeout(updateLibraryChrome,150);setTimeout(updateLibraryChrome,700);setTimeout(updateLibraryChrome,1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',observe);else observe();
